/**
 * The lounge itself: a garden ring, the fenced parquet lounge with its round
 * plaza (info kiosk, welcome sign, benches) and one "corner" per game with a
 * tinted rug, a banner pole and planters as dividers; above it the twisted
 * tower (models/tower.glb, generated by tools/gen-tower.py) with the game
 * room and the rooftop terrace, reached by the elevator pads. Everything else
 * is primitives, no downloads, mobile-cheap. Tables are built by table3d on
 * top of this.
 */
import {
  Billboard,
  BillboardMode,
  ColliderLayer,
  Entity,
  Font,
  GltfContainer,
  InputAction,
  LightSource,
  Material,
  MaterialTransparencyMode,
  MeshCollider,
  MeshRenderer,
  TextAlignMode,
  TextShape,
  TextureWrapMode,
  Transform,
  engine,
  pointerEventsSystem
} from '@dcl/sdk/ecs'
import { Color3, Color4, Quaternion, Vector3 } from '@dcl/sdk/math'
import { BUILT_GAMES, ELEVATORS, FLOORS, LIGHTS, LOUNGE_MAX, LOUNGE_MIN, LOUNGE_SIZE, PALETTE, PLAZA, SCENE_SIZE, SPAWN, ZONES, yawToward, type FloorDef, type ZoneDef, INTERIOR } from './config'
import { GAME_NAMES, getGame } from './games/registry'
import { localeInfo, t as L, uiLang } from './i18n'
import { local } from './tables'
import { board, leaderboardEnabled, leaderboardTicker } from './leaderboard'
import { feedbackEnabled } from './feedback'

/**
 * Text labels that follow the UI language: each entry re-renders its text
 * when the player picks another language (relabelSystem below).
 */
const liveLabels: Array<{ entity: Entity; text: () => string }> = []
let labelledLang = ''
function liveLabel(pos: Vector3, text: () => string, fontSize: number, color = Color4.White(), width = 8): Entity {
  const e = label(pos, text(), fontSize, color, width)
  liveLabels.push({ entity: e, text })
  return e
}
export function relabelSystem(): void {
  if (uiLang.code === labelledLang) return
  labelledLang = uiLang.code
  for (const l of liveLabels) TextShape.getMutable(l.entity).text = l.text()
}

// ---------------------------------------------------------------- primitives

function solid(pos: Vector3, scale: Vector3, color: Color4, opts: { collide?: boolean; rotY?: number; parent?: Entity } = {}): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale, rotation: Quaternion.fromEulerDegrees(0, opts.rotY ?? 0, 0), parent: opts.parent })
  MeshRenderer.setBox(e)
  if (opts.collide) MeshCollider.setBox(e)
  Material.setPbrMaterial(e, { albedoColor: color, roughness: 0.9, metallic: 0 })
  return e
}

const PALACE = INTERIOR === 'palace'

function cylinder(pos: Vector3, scale: Vector3, color: Color4, collide = false): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale })
  MeshRenderer.setCylinder(e, 0.5, 0.5)
  if (collide) MeshCollider.setCylinder(e, 0.5, 0.5)
  Material.setPbrMaterial(e, { albedoColor: color, roughness: 0.9, metallic: 0 })
  return e
}

/** A structural column: fluted marble with gold capital and base in the palace finish, plain wood-brown otherwise. */
function column(pos: Vector3, scale: Vector3, collide = true): Entity {
  if (!PALACE) return cylinder(pos, scale, PALETTE.column, collide)
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale })
  MeshRenderer.setCylinder(e, 0.5, 0.5)
  if (collide) MeshCollider.setCylinder(e, 0.5, 0.5)
  // the shaft texture runs bottom -> top once (capital at v = 1); the cylinder's u wraps around
  const shaft = Material.Texture.Common({ src: 'models/palace/column.png', wrapMode: TextureWrapMode.TWM_CLAMP })
  Material.setPbrMaterial(e, { texture: shaft, albedoColor: Color4.White(), roughness: 0.4, metallic: 0, emissiveTexture: shaft, emissiveColor: Color3.create(1, 0.97, 0.92), emissiveIntensity: 0.18 })
  return e
}

function texturedBox(pos: Vector3, scale: Vector3, src: string, tiling: [number, number], collide = false, rotY = 0, selfLit = 0): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale, rotation: Quaternion.fromEulerDegrees(0, rotY, 0) })
  MeshRenderer.setBox(e)
  if (collide) MeshCollider.setBox(e)
  const tex = Material.Texture.Common({ src, wrapMode: TextureWrapMode.TWM_REPEAT, tiling: { x: tiling[0], y: tiling[1] } })
  Material.setPbrMaterial(e, {
    texture: tex,
    roughness: 0.85,
    metallic: 0,
    ...(selfLit > 0 ? { emissiveTexture: tex, emissiveColor: Color3.create(1, 0.97, 0.92), emissiveIntensity: selfLit } : {})
  })
  return e
}

/**
 * Round rug: the neutral rug texture tinted by `tint`, lying flat, with a
 * glowing edge ring in `glow` (emissive mask images/rug-ring.png) so every
 * game corner reads from a distance without an extra entity.
 */
export function rug(pos: Vector3, size: number, tint: Color4, y = 0.012, glow?: Color4): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(pos.x, y, pos.z), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(size, size, 1) })
  MeshRenderer.setPlane(e)
  const g = glow ?? tint
  Material.setPbrMaterial(e, {
    texture: Material.Texture.Common({ src: 'images/rug.png' }),
    albedoColor: tint,
    emissiveTexture: Material.Texture.Common({ src: 'images/rug-ring.png' }),
    emissiveColor: Color3.create(g.r, g.g, g.b),
    emissiveIntensity: 1.6,
    transparencyMode: MaterialTransparencyMode.MTM_ALPHA_TEST,
    alphaTest: 0.5,
    roughness: 1,
    metallic: 0,
    castShadows: false
  })
  return e
}

function label(pos: Vector3, text: string, fontSize: number, color = Color4.White(), width = 8): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos })
  TextShape.create(e, {
    text,
    fontSize,
    font: Font.F_SANS_SERIF,
    textAlign: TextAlignMode.TAM_MIDDLE_CENTER,
    textColor: color,
    outlineWidth: 0.2,
    outlineColor: Color3.Black(),
    width,
    height: 2
  })
  Billboard.create(e, { billboardMode: BillboardMode.BM_Y })
  return e
}

// ---------------------------------------------------------------- furniture

/**
 * Prop instance: one entity with a shared GLB (models/*.glb from
 * tools/gen-models.py). Every prop used to be two to six primitives with a
 * material each; as instances they share mesh and materials, which is what
 * keeps the phone's material count in budget.
 */
function prop(src: string, pos: Vector3, rotY = 0, scale = 1, collide = false): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, rotation: Quaternion.fromEulerDegrees(0, rotY, 0), scale: Vector3.create(scale, scale, scale) })
  GltfContainer.create(e, { src, visibleMeshesCollisionMask: collide ? ColliderLayer.CL_PHYSICS : ColliderLayer.CL_NONE, invisibleMeshesCollisionMask: ColliderLayer.CL_PHYSICS })
  return e
}

function planter(x: number, z: number, y = 0): void {
  prop(finish('planter'), Vector3.create(x, y, z), 0, 1, true)
}

/** Garden tree (trunk + two leaf balls), `size` scales the whole tree. */
function tree(x: number, z: number, size = 1): void {
  prop('models/tree.glb', Vector3.create(x, 0, z), (x * 37 + z * 11) % 360, size, true)
}

function lamp(x: number, z: number, y = 0): void {
  prop(finish('lamp'), Vector3.create(x, y, z), 45)
}

/** A bench facing `toward` (models/bench.glb). */
function bench(pos: Vector3, toward: Vector3): void {
  prop(finish('bench'), pos, yawToward(pos, toward), 1, true)
}
/** Model path of a lounge prop in the current finish (every prop below has a marble + brass palace variant). */
function finish(name: 'sofa' | 'bar' | 'bench' | 'board' | 'kiosk' | 'shaft' | 'gateway' | 'lamp' | 'planter' | 'plazatree'): string {
  return PALACE ? `models/${name}-palace.glb` : `models/${name}.glb`
}

/**
 * Walkable ring path around a floor's centre: a light carpet runner (alpha-cut plane
 * textured with a ring) that furniture keeps off. `outer` is the ring's outer radius;
 * the inner radius comes from the texture (path-a 0.786, path-b 0.654 of outer).
 */
function pathRing(y: number, outer: number, tex: string): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(PLAZA.x, y + 0.006, PLAZA.z), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(outer * 2, outer * 2, 1) })
  MeshRenderer.setPlane(e)
  // a touch of self-light keeps the runner cream under the purple night sky instead of turning it magenta;
  // in the palace finish the cream texture is tinted to a deep red carpet on the marble
  const tint = PALACE ? PALETTE.runnerRed : Color4.White()
  const glow = PALACE ? Color3.create(0.9, 0.35, 0.35) : Color3.create(1, 0.96, 0.9)
  Material.setPbrMaterial(e, { texture: Material.Texture.Common({ src: tex }), albedoColor: tint, roughness: 1, metallic: 0, castShadows: false, transparencyMode: MaterialTransparencyMode.MTM_ALPHA_TEST, alphaTest: 0.5, emissiveTexture: Material.Texture.Common({ src: tex }), emissiveColor: glow, emissiveIntensity: PALACE ? 0.16 : 0.22 })
  return e
}

/** Banner pole with a coloured cloth and the game name, marking a corner. */
function zoneBanner(z: ZoneDef): void {
  // pole stands on the outer side of the corner (away from the plaza)
  const y = z.position.y
  const centre = Vector3.create(PLAZA.x, y, PLAZA.z)
  const away = Vector3.normalize(Vector3.subtract(z.position, centre))
  const pos = Vector3.add(z.position, Vector3.scale(away, 2.6))
  cylinder(Vector3.create(pos.x, y + 1.7, pos.z), Vector3.create(0.12, 3.4, 0.12), PALACE ? PALETTE.brass : PALETTE.woodDark, true)
  const cloth = engine.addEntity()
  Transform.create(cloth, {
    position: Vector3.create(pos.x, y + 2.35, pos.z),
    rotation: Quaternion.fromEulerDegrees(0, yawToward(pos, centre), 0),
    scale: Vector3.create(0.9, 1.7, 1)
  })
  MeshRenderer.setPlane(cloth)
  Material.setPbrMaterial(cloth, { albedoColor: z.banner, roughness: 0.9, metallic: 0, castShadows: false })
  const built = BUILT_GAMES.includes(z.gameId)
  const name = () => localeInfo(uiLang.code).games[z.gameId]?.name ?? GAME_NAMES[z.gameId]
  // big billboard name high above the corner: readable from the entrance and from the other floors
  liveLabel(Vector3.create(pos.x, y + 5.4, pos.z), () => (built ? name() : `${name()}\n${L().comingSoon}`), built ? 3.4 : 2.2, Color4.White(), 12)
}

/**
 * Elevator shaft: four slim posts and translucent glass on the sides away
 * from the plaza run from the ground to above the rooftop, so the shaft reads
 * as one elevator from anywhere in the lounge; on every floor a glowing pad
 * (standing on it opens the floor panel, see tables.ts / ui.tsx), a light
 * ring and an ELEVATOR sign facing the plaza.
 */
function elevatorShaft(pad: Vector3): void {
  // models/shaft.glb: posts, glass on three sides (open towards -Z = the plaza), roof, pads + light rings on every floor
  prop(finish('shaft'), Vector3.create(pad.x, 0, pad.z), yawToward(pad, PLAZA))
  for (const f of FLOORS) {
    liveLabel(Vector3.create(pad.x, f.y + 3.05, pad.z), () => L().elevator, 2.0, Color4.White(), 6)
    liveLabel(Vector3.create(pad.x, f.y + 2.35, pad.z), () => L().floors.join(' · '), 0.9, PALETTE.cream, 6)
  }
}

/** Directory: which games are on which floor, in the UI language (models/board.glb + a live label). */
function directoryBoard(x: number, z: number): void {
  const yaw = 90 // plate faces east, towards the spawn
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(x, 2.2, z), rotation: Quaternion.fromEulerDegrees(0, yaw, 0) })
  GltfContainer.create(e, { src: finish('board') })
  const text = (): string => {
    const names = (floor: number) =>
      ZONES.filter((zn) => zn.floor === floor && BUILT_GAMES.includes(zn.gameId))
        .map((zn) => localeInfo(uiLang.code).games[zn.gameId]?.name ?? GAME_NAMES[zn.gameId])
        .join(' · ')
    const f = L().floors
    return `${f[0].toUpperCase()}\n${names(0)}\n\n${f[1].toUpperCase()} ▲\n${names(1)}\n\n${f[2].toUpperCase()} ▲▲\n${names(2)}\n\n${f[3].toUpperCase()} ▲▲▲`
  }
  const lbl = engine.addEntity()
  // text shapes read from their -Z side: turn the label the other way round than the plate
  Transform.create(lbl, { position: Vector3.create(x + 0.06, 2.2, z), rotation: Quaternion.fromEulerDegrees(0, yaw + 180, 0) })
  TextShape.create(lbl, { text: text(), fontSize: 0.95, font: Font.F_SANS_SERIF, textAlign: TextAlignMode.TAM_MIDDLE_CENTER, textColor: PALETTE.cream, width: 2.4, height: 1.8, textWrapping: true })
  liveLabels.push({ entity: lbl, text })
}

/** A post with a glowing "?" cube: tap to open How to play. */
function infoKiosk(x: number, z: number): void {
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(x, 0, z), rotation: Quaternion.fromEulerDegrees(0, 45, 0) })
  GltfContainer.create(e, { src: finish('kiosk'), invisibleMeshesCollisionMask: ColliderLayer.CL_POINTER, visibleMeshesCollisionMask: ColliderLayer.CL_NONE })
  label(Vector3.create(x, 1.45, z), '?', 4, Color4.White(), 2)
  liveLabel(Vector3.create(x, 2.05, z), () => L().howToPlay, 1.4, Color4.White(), 4)
  pointerEventsSystem.onPointerDown({ entity: e, opts: { button: InputAction.IA_POINTER, hoverText: 'How to play', maxDistance: 10 } }, () => {
    local.helpOpen = true
  })
}

/**
 * Suggestion box (ideas + bugs) beside the entrance: a brass letter box on a
 * marble pedestal (models/postbox.glb); clicking it opens the feedback panel.
 */
function feedbackBox(x: number, z: number): void {
  if (!feedbackEnabled()) return
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(x, 0, z), rotation: Quaternion.fromEulerDegrees(0, -45, 0) })
  GltfContainer.create(e, { src: 'models/postbox.glb', invisibleMeshesCollisionMask: ColliderLayer.CL_POINTER, visibleMeshesCollisionMask: ColliderLayer.CL_NONE })
  liveLabel(Vector3.create(x, 2.05, z), () => L().feedbackSign, 1.1, PALETTE.brass, 4)
  pointerEventsSystem.onPointerDown({ entity: e, opts: { button: InputAction.IA_POINTER, hoverText: 'Ideas & bugs', maxDistance: 10 } }, () => {
    local.feedbackOpen = true
    local.feedbackState = 'idle'
  })
}

// ---------------------------------------------------------------- scene

export function buildLounge(): void {
  const half = SCENE_SIZE / 2
  const lc = LOUNGE_MIN + LOUNGE_SIZE / 2 // lounge centre (x and z)

  // ground: one collider slab under the whole scene, lawn on top, parquet on the lounge
  solid(Vector3.create(half, -0.05, half), Vector3.create(SCENE_SIZE, 0.1, SCENE_SIZE), PALETTE.floor, { collide: true })
  const lawn = engine.addEntity()
  Transform.create(lawn, { position: Vector3.create(half, 0.001, half), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(SCENE_SIZE, SCENE_SIZE, 1) })
  MeshRenderer.setPlane(lawn)
  Material.setPbrMaterial(lawn, { albedoColor: PALETTE.lawn, roughness: 1, metallic: 0, castShadows: false })
  const parquet = engine.addEntity()
  Transform.create(parquet, { position: Vector3.create(lc, 0.003, lc), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(LOUNGE_SIZE, LOUNGE_SIZE, 1) })
  MeshRenderer.setPlane(parquet)
  // palace: marble tiles on a 4 m repeat (2 m tiles); lounge: dark parquet
  const floorTex = Material.Texture.Common({ src: PALACE ? 'models/palace/floor.png' : 'images/floor.png', wrapMode: TextureWrapMode.TWM_REPEAT, tiling: PALACE ? { x: LOUNGE_SIZE / 4, y: LOUNGE_SIZE / 4 } : { x: 10, y: 10 } })
  Material.setPbrMaterial(parquet, {
    texture: floorTex,
    roughness: PALACE ? 0.35 : 0.75,
    metallic: 0,
    castShadows: false,
    // palace marble keeps a little of its own light so the purple night ambient does not turn it lavender
    ...(PALACE ? { emissiveTexture: floorTex, emissiveColor: Color3.create(1, 0.97, 0.92), emissiveIntensity: 0.18 } : {})
  })

  // low wooden boundary around the lounge so nobody walks off the parquet on a
  // phone, with a cap rail; the entrance gap is in the south wall
  const wallH = 0.9
  const wallT = 0.3
  const gap = 4.2 // entrance width, centred on the spawn
  const west = LOUNGE_MIN + (SPAWN.x - gap / 2 - LOUNGE_MIN) / 2
  const east = SPAWN.x + gap / 2 + (LOUNGE_MAX - SPAWN.x - gap / 2) / 2
  const wLen = SPAWN.x - gap / 2 - LOUNGE_MIN
  const eLen = LOUNGE_MAX - SPAWN.x - gap / 2
  // palace: marble panels (2:1, engraved frieze along the top) with a brass cap rail; lounge: wood
  const wallTex = PALACE ? 'models/palace/wall.png' : 'images/wood.png'
  const panels = (len: number): [number, number] => (PALACE ? [Math.max(1, Math.round(len / (wallH * 2))), 1] : [len < 10 ? 3.5 : 8, 1])
  const rail = PALACE ? PALETTE.brass : PALETTE.woodDark
  const lit = PALACE ? 0.16 : 0
  texturedBox(Vector3.create(west, wallH / 2, LOUNGE_MIN + wallT / 2), Vector3.create(wLen, wallH, wallT), wallTex, panels(wLen), true, 0, lit)
  texturedBox(Vector3.create(east, wallH / 2, LOUNGE_MIN + wallT / 2), Vector3.create(eLen, wallH, wallT), wallTex, panels(eLen), true, 0, lit)
  texturedBox(Vector3.create(lc, wallH / 2, LOUNGE_MAX - wallT / 2), Vector3.create(LOUNGE_SIZE, wallH, wallT), wallTex, panels(LOUNGE_SIZE), true, 0, lit)
  texturedBox(Vector3.create(LOUNGE_MIN + wallT / 2, wallH / 2, lc), Vector3.create(LOUNGE_SIZE, wallH, wallT), wallTex, panels(LOUNGE_SIZE), true, 90, lit)
  texturedBox(Vector3.create(LOUNGE_MAX - wallT / 2, wallH / 2, lc), Vector3.create(LOUNGE_SIZE, wallH, wallT), wallTex, panels(LOUNGE_SIZE), true, 90, lit)
  solid(Vector3.create(west, wallH + 0.03, LOUNGE_MIN + wallT / 2), Vector3.create(wLen, 0.06, wallT + 0.1), rail)
  solid(Vector3.create(east, wallH + 0.03, LOUNGE_MIN + wallT / 2), Vector3.create(eLen, 0.06, wallT + 0.1), rail)
  solid(Vector3.create(lc, wallH + 0.03, LOUNGE_MAX - wallT / 2), Vector3.create(LOUNGE_SIZE, 0.06, wallT + 0.1), rail)
  solid(Vector3.create(LOUNGE_MIN + wallT / 2, wallH + 0.03, lc), Vector3.create(wallT + 0.1, 0.06, LOUNGE_SIZE), rail)
  solid(Vector3.create(LOUNGE_MAX - wallT / 2, wallH + 0.03, lc), Vector3.create(wallT + 0.1, 0.06, LOUNGE_SIZE), rail)

  // garden ring outside the fence: a path from the scene edge to the entrance,
  // trees and lamps, and the scene edge kept walkable-safe by the fence itself
  const path = engine.addEntity()
  Transform.create(path, { position: Vector3.create(SPAWN.x, 0.002, LOUNGE_MIN / 2), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(gap, LOUNGE_MIN, 1) })
  MeshRenderer.setPlane(path)
  Material.setPbrMaterial(path, { albedoColor: PALETTE.path, roughness: 1, metallic: 0, castShadows: false })
  for (const [x, z, sz] of [[4, 4, 1.1], [4, 44, 1.0], [44, 4, 1.15], [44, 44, 1.05], [4, 24, 0.9], [44, 24, 0.95], [24, 44.5, 1.1], [13, 3.5, 0.85], [35, 3.5, 0.9], [4, 14, 0.8], [44, 34, 0.8]]) {
    tree(x, z, sz)
  }
  for (const [x, z] of [[SPAWN.x - 3, 3], [SPAWN.x + 3, 3], [3, 40], [45, 40], [3, 8], [45, 8]]) lamp(x, z)

  // the plaza: a big warm rug, a tree in the middle as the landmark, four
  // benches facing in, lamps at the corners
  rug(PLAZA, 9.5, Color4.fromHexString('#e3c9a3ff'), 0.008, Color4.fromHexString('#ffd27aff'))
  prop(finish('plazatree'), Vector3.create(PLAZA.x, 0, PLAZA.z), 0, 1, true)
  for (const [x, z] of [[PLAZA.x - 3.6, PLAZA.z + 2.6], [PLAZA.x + 3.6, PLAZA.z + 2.6], [PLAZA.x - 3.6, PLAZA.z - 2.6], [PLAZA.x + 3.6, PLAZA.z - 2.6]]) {
    bench(Vector3.create(x, 0, z), PLAZA)
  }
  lamp(PLAZA.x, PLAZA.z + 7)
  lamp(PLAZA.x - 6.5, PLAZA.z)
  lamp(PLAZA.x + 6.5, PLAZA.z)

  // corners on every floor: rug + banner (planters between ground-floor neighbours)
  for (const z of ZONES) {
    // upper floors get tighter rugs (the annular slabs need a walkway inside and outside the
    // tables), except under a four-seat table, which needs room on every side
    const fourSeats = (getGame(z.gameId).seats ?? 2) > 2
    // rug sizes keep clear of the walking ring inside the seats: 6.8 m for a ground pair, 5.4 m for a pair on a slab
    if (BUILT_GAMES.includes(z.gameId)) rug(z.position, z.tables > 1 ? (z.floor > 0 ? 5.4 : 6.8) : z.floor > 0 && !fourSeats ? 4.4 : 5.6, z.rug, z.position.y + 0.012, z.banner)
    zoneBanner(z)
  }
  const ground = ZONES.filter((z) => z.floor === 0)
  for (let i = 0; i < ground.length; i++) {
    const a = ground[i].position
    const b = ground[(i + 1) % ground.length].position
    // skip the gap between the two southern corners: that is the entrance
    if (Vector3.distance(a, b) > 14) continue
    const mid = Vector3.scale(Vector3.add(a, b), 0.5)
    const away = Vector3.normalize(Vector3.subtract(mid, PLAZA))
    const p = Vector3.add(mid, Vector3.scale(away, 1.2))
    if (ELEVATORS.some((e) => Vector3.distance(Vector3.create(e.x, 0, e.z), p) < 2.6)) continue
    planter(p.x, p.z)
  }
  planter(LOUNGE_MIN + 2.6, LOUNGE_MIN + 2.6)
  planter(LOUNGE_MAX - 2.6, LOUNGE_MIN + 2.6)
  planter(LOUNGE_MIN + 2.6, LOUNGE_MAX - 2.6)
  planter(LOUNGE_MAX - 2.6, LOUNGE_MAX - 2.6)

  // entrance sequence (south to north): portal, bars flanking the path, gateway with the
  // welcome sign, then the ring path; kiosk and directory sit off the path to the west
  const gz = PLAZA.z - 8.6
  prop(finish('gateway'), Vector3.create(SPAWN.x, 0, gz), 0, 1, true)
  liveLabel(Vector3.create(SPAWN.x, 4.2, gz), () => L().welcome, 1.6, PALETTE.cream, 12)
  infoKiosk(20.3, 16.0)
  feedbackBox(27.7, 16.0)
  directoryBoard(18.9, 14.9)

  buildTower()

  // real lights on top of the emissive fixtures (see config LIGHTS)
  for (const l of LIGHTS) {
    const e = engine.addEntity()
    Transform.create(e, { position: Vector3.create(l.x, l.y, l.z) })
    LightSource.create(e, { type: LightSource.Type.Point({}), color: l.color, intensity: l.intensity, range: l.range, shadow: false })
  }
}

/**
 * The twisted tower: one GLB for ribs, slabs, railings and their colliders
 * (tools/gen-tower.py), plus primitive columns, the elevator pads and the
 * furniture of the game room and the rooftop terrace.
 */
function buildTower(): void {
  const tower = engine.addEntity()
  Transform.create(tower, { position: Vector3.create(PLAZA.x, 0, PLAZA.z) })
  GltfContainer.create(tower, { src: PALACE ? 'models/tower-palace.glb' : 'models/tower.glb' })
  // glass facade with the entrance portal, string lights (models/decor.glb, same origin)
  const decor = engine.addEntity()
  Transform.create(decor, { position: Vector3.create(PLAZA.x, 0, PLAZA.z) })
  GltfContainer.create(decor, { src: 'models/decor.glb', visibleMeshesCollisionMask: ColliderLayer.CL_NONE, invisibleMeshesCollisionMask: ColliderLayer.CL_PHYSICS })
  // the name over the portal is baked neon geometry in decor.glb (tools/gen-models.py)

  // lounge furniture: sofa pairs close to the plaza tree (inside the ring path), two bars
  // flanking the entrance path just inside the portal
  for (const deg of [22, 158, 202, 338]) {
    const t = (deg * Math.PI) / 180
    const pos = Vector3.create(PLAZA.x + Math.sin(t) * 4.6, 0, PLAZA.z + Math.cos(t) * 4.6)
    prop(finish('sofa'), pos, yawToward(pos, PLAZA) + 180, 1, true)
  }
  prop(finish('bar'), Vector3.create(21.4, 0, 11.9), 90, 1, true)
  prop(finish('bar'), Vector3.create(26.6, 0, 11.9), -90, 1, true)

  // the walkable ring on every floor: one alpha-cut runner plane each, clear of furniture and seats,
  // 2 m+ wide (path-a inner/outer 0.705: ground 5.4..7.6, game room 5.2..7.4, rooftop 4.65..6.6; path-b 0.60: sky room 3.4..5.7)
  pathRing(FLOORS[0].y, 7.6, 'images/path-a.png')
  pathRing(FLOORS[1].y, 7.4, 'images/path-a.png')
  pathRing(FLOORS[2].y, 5.7, 'images/path-b.png')
  pathRing(FLOORS[3].y, 6.6, 'images/path-a.png')

  // columns carrying the slabs, between the corners so they never block a table
  const columnAt = (deg: number, r: number, y0: number, y1: number, thick: number) => {
    const t = (deg * Math.PI) / 180
    column(Vector3.create(PLAZA.x + Math.sin(t) * r, (y0 + y1) / 2, PLAZA.z + Math.cos(t) * r), Vector3.create(thick, y1 - y0, thick), true)
  }
  // ground: between the corners, two flanking the entrance path; game room: between its corners
  for (const deg of [160, 200, 262, 304, 0, 56, 101]) columnAt(deg, 11.4, 0, 8, 0.6)
  for (const deg of [112, 158, 202, 338]) columnAt(deg, 10.4, 8, 16, 0.5) // between the game-room corners, clear of both elevators and of the walkways

  for (const pad of ELEVATORS) elevatorShaft(pad)

  // game room (floor 1): the ring stays clear so people can walk around it (no planters here)
  const y1 = FLOORS[1].y
  liveLabel(Vector3.create(PLAZA.x, y1 + 3.2, PLAZA.z + 5.2), () => L().gameRoom, 2.6, Color4.White(), 8)

  // sky room (floor 2): two game corners (N, S), sofas at E and W looking over the oculus, planters, lamps
  const y2 = FLOORS[2].y
  for (const deg of [45, 120, 225]) columnAt(deg, 9.5, 16, 24, 0.5)
  for (const deg of [90, 270]) {
    const t = (deg * Math.PI) / 180
    const pos = Vector3.create(PLAZA.x + Math.sin(t) * 7.0, y2, PLAZA.z + Math.cos(t) * 7.0)
    prop(finish('sofa'), pos, yawToward(pos, PLAZA) + 180, 1, true)
  }
  liveLabel(Vector3.create(PLAZA.x, y2 + 3.2, PLAZA.z + 4.4), () => L().skyRoom, 2.6, Color4.White(), 8)

  // rooftop terrace (floor 3): benches looking down the oculus, planters, a sign under the crown
  const y3 = FLOORS[3].y
  const roofCentre = Vector3.create(PLAZA.x, y3, PLAZA.z)
  // benches look down the oculus; in the palace finish four marble pavilions stand between them
  for (const deg of PALACE ? [22, 90, 158, 202, 270, 338] : [30, 100, 170, 260, 330]) {
    const t = (deg * Math.PI) / 180
    bench(Vector3.create(PLAZA.x + Math.sin(t) * 7.2, y3, PLAZA.z + Math.cos(t) * 7.2), roofCentre)
  }
  if (PALACE) {
    for (const deg of [45, 135, 225, 315]) {
      const t = (deg * Math.PI) / 180
      const pos = Vector3.create(PLAZA.x + Math.sin(t) * 8.0, y3, PLAZA.z + Math.cos(t) * 8.0)
      prop('models/pavilion.glb', pos, deg, 1, true)
    }
  }
  planter(PLAZA.x - 8.9, PLAZA.z + 3, y3)
  planter(PLAZA.x + 8.9, PLAZA.z + 3, y3)
  liveLabel(Vector3.create(PLAZA.x, y3 + 3.4, PLAZA.z - 7.0), () => L().rooftop, 2.6, Color4.White(), 8) // south, clear of the board
  if (leaderboardEnabled()) leaderboardBoard(Vector3.create(PLAZA.x, y3, PLAZA.z + 8.4))
  else liveLabel(Vector3.create(PLAZA.x, y3 + 2.2, PLAZA.z + 7.0), () => L().rooftopNote, 1.1, PALETTE.cream, 10)
}

/**
 * The rooftop leaderboard: the directory board model with the ranked rows as
 * monospace text, refreshed while somebody is on the rooftop (see
 * leaderboardSystem). Faces south (readers come from the elevators / oculus).
 */
function leaderboardBoard(pos: Vector3): void {
  // board.glb is a 2.6 x 1.9 plate on a 2.2 m pole; at 1.5x the plate is 3.9 x 2.85 with its
  // centre 2.6 m up. TextShapes read from their -Z side, and the readers stand south (-Z).
  prop(finish('board'), Vector3.create(pos.x, pos.y + 2.6, pos.z), 0, 1.5, true)
  const title = engine.addEntity()
  Transform.create(title, { position: Vector3.create(pos.x, pos.y + 3.72, pos.z - 0.14) })
  TextShape.create(title, { text: '', fontSize: 2.2, font: Font.F_SANS_SERIF, textAlign: TextAlignMode.TAM_MIDDLE_CENTER, textColor: PALETTE.cream, width: 5, height: 0.7 })
  const body = engine.addEntity()
  Transform.create(body, { position: Vector3.create(pos.x, pos.y + 2.35, pos.z - 0.14) })
  TextShape.create(body, { text: '', fontSize: 1.35, font: Font.F_MONOSPACE, textAlign: TextAlignMode.TAM_MIDDLE_CENTER, textColor: Color4.White(), width: 4.2, height: 2.4 })
  let shownVersion = -1
  let shownLang = ''
  engine.addSystem((dt) => {
    leaderboardTicker(dt, local.floor === 3)
    if (board.version === shownVersion && uiLang.code === shownLang) return
    shownVersion = board.version
    shownLang = uiLang.code
    const str = L()
    TextShape.getMutable(title).text = str.leaderboardTitle
    const rows = board.rows.slice(0, 10)
    TextShape.getMutable(body).text = rows.length === 0
      ? (board.failed ? str.leaderboardOffline : str.leaderboardEmpty)
      : rows.map((r) => `${String(r.rank).padStart(2, ' ')}. ${r.name.slice(0, 14).padEnd(14, ' ')} ${String(r.wins).padStart(3, ' ')} ${str.winsShort}  ${str.streakShort} ${r.streak}`).join('\n')
  })
}
