/**
 * The lounge itself: a garden ring, the fenced parquet lounge with its round
 * plaza (info kiosk, welcome sign, benches) and one "corner" per game with a
 * tinted rug, a banner pole and planters as dividers; above it the twisted
 * tower (models/tower.glb, generated by tools/gen-tower.py) with the game
 * room and the rooftop terrace, reached by the elevator pads. Everything else
 * is primitives, no downloads, mobile-cheap. Tables are built by table3d on
 * top of this.
 */
import {
  Billboard,
  BillboardMode,
  ColliderLayer,
  Entity,
  Font,
  GltfContainer,
  InputAction,
  Material,
  MaterialTransparencyMode,
  MeshCollider,
  MeshRenderer,
  TextAlignMode,
  TextShape,
  TextureWrapMode,
  Transform,
  engine,
  pointerEventsSystem
} from '@dcl/sdk/ecs'
import { Color3, Color4, Quaternion, Vector3 } from '@dcl/sdk/math'
import { BUILT_GAMES, ELEVATOR, FLOORS, LOUNGE_MAX, LOUNGE_MIN, LOUNGE_SIZE, PALETTE, PLAZA, SCENE_SIZE, SPAWN, ZONES, yawToward, type FloorDef, type ZoneDef } from './config'
import { GAME_NAMES } from './games/registry'
import { local } from './tables'

// ---------------------------------------------------------------- primitives

function solid(pos: Vector3, scale: Vector3, color: Color4, opts: { collide?: boolean; rotY?: number; parent?: Entity } = {}): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale, rotation: Quaternion.fromEulerDegrees(0, opts.rotY ?? 0, 0), parent: opts.parent })
  MeshRenderer.setBox(e)
  if (opts.collide) MeshCollider.setBox(e)
  Material.setPbrMaterial(e, { albedoColor: color, roughness: 0.9, metallic: 0 })
  return e
}

function cylinder(pos: Vector3, scale: Vector3, color: Color4, collide = false): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale })
  MeshRenderer.setCylinder(e, 0.5, 0.5)
  if (collide) MeshCollider.setCylinder(e, 0.5, 0.5)
  Material.setPbrMaterial(e, { albedoColor: color, roughness: 0.9, metallic: 0 })
  return e
}

function texturedBox(pos: Vector3, scale: Vector3, src: string, tiling: [number, number], collide = false, rotY = 0): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale, rotation: Quaternion.fromEulerDegrees(0, rotY, 0) })
  MeshRenderer.setBox(e)
  if (collide) MeshCollider.setBox(e)
  Material.setPbrMaterial(e, {
    texture: Material.Texture.Common({ src, wrapMode: TextureWrapMode.TWM_REPEAT, tiling: { x: tiling[0], y: tiling[1] } }),
    roughness: 0.85,
    metallic: 0
  })
  return e
}

/** Round rug: the neutral rug texture tinted by `tint`, lying flat. */
export function rug(pos: Vector3, size: number, tint: Color4, y = 0.012): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(pos.x, y, pos.z), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(size, size, 1) })
  MeshRenderer.setPlane(e)
  Material.setPbrMaterial(e, {
    texture: Material.Texture.Common({ src: 'images/rug.png' }),
    albedoColor: tint,
    transparencyMode: MaterialTransparencyMode.MTM_ALPHA_TEST,
    alphaTest: 0.5,
    roughness: 1,
    metallic: 0,
    castShadows: false
  })
  return e
}

function label(pos: Vector3, text: string, fontSize: number, color = Color4.White(), width = 8): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos })
  TextShape.create(e, {
    text,
    fontSize,
    font: Font.F_SANS_SERIF,
    textAlign: TextAlignMode.TAM_MIDDLE_CENTER,
    textColor: color,
    outlineWidth: 0.2,
    outlineColor: Color3.Black(),
    width,
    height: 2
  })
  Billboard.create(e, { billboardMode: BillboardMode.BM_Y })
  return e
}

// ---------------------------------------------------------------- furniture

/** Low-poly leaf ball (models/canopy.glb, 320 triangles; a primitive sphere costs ~770). */
function canopy(pos: Vector3, scale: Vector3): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale })
  GltfContainer.create(e, { src: 'models/canopy.glb' })
  return e
}

function planter(x: number, z: number, y = 0): void {
  cylinder(Vector3.create(x, y + 0.3, z), Vector3.create(0.9, 0.6, 0.9), PALETTE.pot, true)
  canopy(Vector3.create(x, y + 1.05, z), Vector3.create(1.2, 1.0, 1.2))
}

/** Garden tree: trunk + two leaf balls. */
function tree(x: number, z: number, size = 1): void {
  cylinder(Vector3.create(x, 1.6 * size, z), Vector3.create(0.36 * size, 3.2 * size, 0.36 * size), PALETTE.woodDark, true)
  for (const [dx, dy, dz, r] of [[0, 3.6, 0, 2.6], [0.6, 4.4, -0.4, 1.7]]) {
    canopy(Vector3.create(x + dx * size, dy * size, z + dz * size), Vector3.create(r * size, r * 0.85 * size, r * size))
  }
}

/** Glowing cube lantern (a sphere would cost 770 triangles). */
function lantern(pos: Vector3, size: number): void {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, rotation: Quaternion.fromEulerDegrees(0, 45, 0), scale: Vector3.create(size, size, size) })
  MeshRenderer.setBox(e)
  Material.setPbrMaterial(e, { albedoColor: PALETTE.lamp, emissiveColor: Color3.fromHexString('#ffc773'), emissiveIntensity: 3, roughness: 0.3, metallic: 0 })
}

function lamp(x: number, z: number, y = 0): void {
  cylinder(Vector3.create(x, y + 1.4, z), Vector3.create(0.12, 2.8, 0.12), PALETTE.woodDark, true)
  lantern(Vector3.create(x, y + 2.95, z), 0.4)
}

/** A bench facing `toward`, made of a seat plank and two legs. */
function bench(pos: Vector3, toward: Vector3): void {
  const yaw = yawToward(pos, toward)
  const root = engine.addEntity()
  Transform.create(root, { position: pos, rotation: Quaternion.fromEulerDegrees(0, yaw, 0) })
  solid(Vector3.create(0, 0.42, 0), Vector3.create(1.8, 0.08, 0.5), PALETTE.wood, { parent: root, collide: true })
  solid(Vector3.create(-0.7, 0.2, 0), Vector3.create(0.12, 0.4, 0.44), PALETTE.woodDark, { parent: root })
  solid(Vector3.create(0.7, 0.2, 0), Vector3.create(0.12, 0.4, 0.44), PALETTE.woodDark, { parent: root })
}

/** Banner pole with a coloured cloth and the game name, marking a corner. */
function zoneBanner(z: ZoneDef): void {
  // pole stands on the outer side of the corner (away from the plaza)
  const y = z.position.y
  const centre = Vector3.create(PLAZA.x, y, PLAZA.z)
  const away = Vector3.normalize(Vector3.subtract(z.position, centre))
  const pos = Vector3.add(z.position, Vector3.scale(away, 2.6))
  cylinder(Vector3.create(pos.x, y + 1.7, pos.z), Vector3.create(0.12, 3.4, 0.12), PALETTE.woodDark, true)
  const cloth = engine.addEntity()
  Transform.create(cloth, {
    position: Vector3.create(pos.x, y + 2.35, pos.z),
    rotation: Quaternion.fromEulerDegrees(0, yawToward(pos, centre), 0),
    scale: Vector3.create(0.9, 1.7, 1)
  })
  MeshRenderer.setPlane(cloth)
  Material.setPbrMaterial(cloth, { albedoColor: z.banner, roughness: 0.9, metallic: 0, castShadows: false })
  const built = BUILT_GAMES.includes(z.gameId)
  label(Vector3.create(pos.x, y + 3.75, pos.z), built ? GAME_NAMES[z.gameId] : `${GAME_NAMES[z.gameId]}\ncoming soon`, built ? 2.2 : 1.6, Color4.White(), 8)
}

/** Glowing round pad + post: standing on it opens the elevator panel (see tables.ts / ui.tsx). */
function elevatorPad(f: FloorDef): void {
  const y = f.y
  const pad = engine.addEntity()
  Transform.create(pad, { position: Vector3.create(ELEVATOR.x, y + 0.02, ELEVATOR.z), scale: Vector3.create(2.2, 0.04, 2.2) })
  MeshRenderer.setCylinder(pad, 0.5, 0.5)
  Material.setPbrMaterial(pad, { albedoColor: Color4.fromHexString('#7fd0e0ff'), emissiveColor: Color3.fromHexString('#3fc1d9'), emissiveIntensity: 1.2, roughness: 0.4, metallic: 0.1 })
  cylinder(Vector3.create(ELEVATOR.x, y + 1.1, ELEVATOR.z - 1.3), Vector3.create(0.14, 2.2, 0.14), PALETTE.woodDark, true)
  const cube = engine.addEntity()
  Transform.create(cube, { position: Vector3.create(ELEVATOR.x, y + 2.35, ELEVATOR.z - 1.3), rotation: Quaternion.fromEulerDegrees(0, 45, 0), scale: Vector3.create(0.4, 0.4, 0.4) })
  MeshRenderer.setBox(cube)
  Material.setPbrMaterial(cube, { albedoColor: PALETTE.frame, emissiveColor: Color3.fromHexString('#3fc1d9'), emissiveIntensity: 0.8, roughness: 0.3, metallic: 0.2 })
  label(Vector3.create(ELEVATOR.x, y + 2.95, ELEVATOR.z - 1.3), 'Elevator', 1.4, Color4.White(), 4)
  label(Vector3.create(ELEVATOR.x, y + 2.35, ELEVATOR.z - 1.3), '▲▼', 1.4, Color4.White(), 2)
}

/** A post with a glowing "?" cube: tap to open How to play. */
function infoKiosk(x: number, z: number): void {
  cylinder(Vector3.create(x, 0.6, z), Vector3.create(0.14, 1.2, 0.14), PALETTE.woodDark, true)
  const cube = engine.addEntity()
  Transform.create(cube, { position: Vector3.create(x, 1.45, z), rotation: Quaternion.fromEulerDegrees(0, 45, 0), scale: Vector3.create(0.42, 0.42, 0.42) })
  MeshRenderer.setBox(cube)
  MeshCollider.setBox(cube, ColliderLayer.CL_POINTER)
  Material.setPbrMaterial(cube, { albedoColor: PALETTE.frame, emissiveColor: Color3.fromHexString('#3fc1d9'), emissiveIntensity: 0.8, roughness: 0.3, metallic: 0.2 })
  label(Vector3.create(x, 1.45, z), '?', 4, Color4.White(), 2)
  label(Vector3.create(x, 2.05, z), 'How to play', 1.4, Color4.White(), 4)
  pointerEventsSystem.onPointerDown({ entity: cube, opts: { button: InputAction.IA_POINTER, hoverText: 'How to play', maxDistance: 10 } }, () => {
    local.helpOpen = true
  })
}

// ---------------------------------------------------------------- scene

export function buildLounge(): void {
  const half = SCENE_SIZE / 2
  const lc = LOUNGE_MIN + LOUNGE_SIZE / 2 // lounge centre (x and z)

  // ground: one collider slab under the whole scene, lawn on top, parquet on the lounge
  solid(Vector3.create(half, -0.05, half), Vector3.create(SCENE_SIZE, 0.1, SCENE_SIZE), PALETTE.floor, { collide: true })
  const lawn = engine.addEntity()
  Transform.create(lawn, { position: Vector3.create(half, 0.001, half), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(SCENE_SIZE, SCENE_SIZE, 1) })
  MeshRenderer.setPlane(lawn)
  Material.setPbrMaterial(lawn, { albedoColor: PALETTE.lawn, roughness: 1, metallic: 0, castShadows: false })
  const parquet = engine.addEntity()
  Transform.create(parquet, { position: Vector3.create(lc, 0.003, lc), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(LOUNGE_SIZE, LOUNGE_SIZE, 1) })
  MeshRenderer.setPlane(parquet)
  Material.setPbrMaterial(parquet, {
    texture: Material.Texture.Common({ src: 'images/floor.png', wrapMode: TextureWrapMode.TWM_REPEAT, tiling: { x: 10, y: 10 } }),
    roughness: 0.75,
    metallic: 0,
    castShadows: false
  })

  // low wooden boundary around the lounge so nobody walks off the parquet on a
  // phone, with a cap rail; the entrance gap is in the south wall
  const wallH = 0.9
  const wallT = 0.3
  const gap = 4.2 // entrance width, centred on the spawn
  const west = LOUNGE_MIN + (SPAWN.x - gap / 2 - LOUNGE_MIN) / 2
  const east = SPAWN.x + gap / 2 + (LOUNGE_MAX - SPAWN.x - gap / 2) / 2
  const wLen = SPAWN.x - gap / 2 - LOUNGE_MIN
  const eLen = LOUNGE_MAX - SPAWN.x - gap / 2
  texturedBox(Vector3.create(west, wallH / 2, LOUNGE_MIN + wallT / 2), Vector3.create(wLen, wallH, wallT), 'images/wood.png', [3.5, 1], true)
  texturedBox(Vector3.create(east, wallH / 2, LOUNGE_MIN + wallT / 2), Vector3.create(eLen, wallH, wallT), 'images/wood.png', [3.5, 1], true)
  texturedBox(Vector3.create(lc, wallH / 2, LOUNGE_MAX - wallT / 2), Vector3.create(LOUNGE_SIZE, wallH, wallT), 'images/wood.png', [8, 1], true)
  texturedBox(Vector3.create(LOUNGE_MIN + wallT / 2, wallH / 2, lc), Vector3.create(LOUNGE_SIZE, wallH, wallT), 'images/wood.png', [8, 1], true, 90)
  texturedBox(Vector3.create(LOUNGE_MAX - wallT / 2, wallH / 2, lc), Vector3.create(LOUNGE_SIZE, wallH, wallT), 'images/wood.png', [8, 1], true, 90)
  solid(Vector3.create(west, wallH + 0.03, LOUNGE_MIN + wallT / 2), Vector3.create(wLen, 0.06, wallT + 0.1), PALETTE.woodDark)
  solid(Vector3.create(east, wallH + 0.03, LOUNGE_MIN + wallT / 2), Vector3.create(eLen, 0.06, wallT + 0.1), PALETTE.woodDark)
  solid(Vector3.create(lc, wallH + 0.03, LOUNGE_MAX - wallT / 2), Vector3.create(LOUNGE_SIZE, 0.06, wallT + 0.1), PALETTE.woodDark)
  solid(Vector3.create(LOUNGE_MIN + wallT / 2, wallH + 0.03, lc), Vector3.create(wallT + 0.1, 0.06, LOUNGE_SIZE), PALETTE.woodDark)
  solid(Vector3.create(LOUNGE_MAX - wallT / 2, wallH + 0.03, lc), Vector3.create(wallT + 0.1, 0.06, LOUNGE_SIZE), PALETTE.woodDark)

  // garden ring outside the fence: a path from the scene edge to the entrance,
  // trees and lamps, and the scene edge kept walkable-safe by the fence itself
  const path = engine.addEntity()
  Transform.create(path, { position: Vector3.create(SPAWN.x, 0.002, LOUNGE_MIN / 2), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(gap, LOUNGE_MIN, 1) })
  MeshRenderer.setPlane(path)
  Material.setPbrMaterial(path, { albedoColor: PALETTE.path, roughness: 1, metallic: 0, castShadows: false })
  for (const [x, z, sz] of [[4, 4, 1.1], [4, 44, 1.0], [44, 4, 1.15], [44, 44, 1.05], [4, 24, 0.9], [44, 24, 0.95], [24, 44.5, 1.1], [13, 3.5, 0.85], [35, 3.5, 0.9], [4, 14, 0.8], [44, 34, 0.8]]) {
    tree(x, z, sz)
  }
  for (const [x, z] of [[SPAWN.x - 3, 3], [SPAWN.x + 3, 3], [3, 40], [45, 40], [3, 8], [45, 8]]) lamp(x, z)

  // the plaza: a big warm rug, a tree in the middle as the landmark, four
  // benches facing in, lamps at the corners
  rug(PLAZA, 9.5, Color4.fromHexString('#e3c9a3ff'), 0.008)
  cylinder(Vector3.create(PLAZA.x, 0.35, PLAZA.z), Vector3.create(1.6, 0.7, 1.6), PALETTE.pot, true)
  cylinder(Vector3.create(PLAZA.x, 2.0, PLAZA.z), Vector3.create(0.32, 3.4, 0.32), PALETTE.woodDark, true)
  for (const [dx, dy, dz, r] of [[0, 3.9, 0, 3.0], [-1.1, 3.3, 0.6, 2.0], [1.0, 3.5, -0.7, 2.1], [0.4, 4.6, 0.9, 1.7]]) {
    canopy(Vector3.create(PLAZA.x + dx, dy, PLAZA.z + dz), Vector3.create(r, r * 0.8, r))
  }
  for (const [x, z] of [[PLAZA.x - 3.6, PLAZA.z + 2.6], [PLAZA.x + 3.6, PLAZA.z + 2.6], [PLAZA.x - 3.6, PLAZA.z - 2.6], [PLAZA.x + 3.6, PLAZA.z - 2.6]]) {
    bench(Vector3.create(x, 0, z), PLAZA)
  }
  lamp(PLAZA.x, PLAZA.z + 7)
  lamp(PLAZA.x - 6.5, PLAZA.z)
  lamp(PLAZA.x + 6.5, PLAZA.z)

  // corners on every floor: rug + banner (planters between ground-floor neighbours)
  for (const z of ZONES) {
    if (BUILT_GAMES.includes(z.gameId)) rug(z.position, z.tables > 1 ? 8.4 : 5.6, z.rug, z.position.y + 0.012)
    zoneBanner(z)
  }
  const ground = ZONES.filter((z) => z.floor === 0)
  for (let i = 0; i < ground.length; i++) {
    const a = ground[i].position
    const b = ground[(i + 1) % ground.length].position
    // skip the gap between the two southern corners: that is the entrance
    if (Vector3.distance(a, b) > 14) continue
    const mid = Vector3.scale(Vector3.add(a, b), 0.5)
    const away = Vector3.normalize(Vector3.subtract(mid, PLAZA))
    const p = Vector3.add(mid, Vector3.scale(away, 1.2))
    planter(p.x, p.z)
  }
  planter(LOUNGE_MIN + 2.6, LOUNGE_MIN + 2.6)
  planter(LOUNGE_MAX - 2.6, LOUNGE_MIN + 2.6)
  planter(LOUNGE_MIN + 2.6, LOUNGE_MAX - 2.6)
  planter(LOUNGE_MAX - 2.6, LOUNGE_MAX - 2.6)

  // entrance: a wooden gateway over the path with the welcome sign, kiosk beside it
  const gz = SPAWN.z + 3.4
  cylinder(Vector3.create(SPAWN.x - 3.2, 1.7, gz), Vector3.create(0.22, 3.4, 0.22), PALETTE.woodDark, true)
  cylinder(Vector3.create(SPAWN.x + 3.2, 1.7, gz), Vector3.create(0.22, 3.4, 0.22), PALETTE.woodDark, true)
  solid(Vector3.create(SPAWN.x, 3.5, gz), Vector3.create(6.9, 0.22, 0.3), PALETTE.woodDark)
  for (const x of [SPAWN.x - 3.2, SPAWN.x + 3.2]) lantern(Vector3.create(x, 3.75, gz), 0.34)
  label(Vector3.create(SPAWN.x, 4.35, gz), 'ARENA LOUNGE', 3.4, Color4.White(), 10)
  label(Vector3.create(SPAWN.x, 2.95, gz), 'Pick a table, take a seat, play a friend', 1.5, PALETTE.cream, 10)
  infoKiosk(SPAWN.x - 4.6, SPAWN.z + 1.6)

  buildTower()
}

/**
 * The twisted tower: one GLB for ribs, slabs, railings and their colliders
 * (tools/gen-tower.py), plus primitive columns, the elevator pads and the
 * furniture of the game room and the rooftop terrace.
 */
function buildTower(): void {
  const tower = engine.addEntity()
  Transform.create(tower, { position: Vector3.create(PLAZA.x, 0, PLAZA.z) })
  GltfContainer.create(tower, { src: 'models/tower.glb' })

  // columns carrying the slabs, between the corners so they never block a table
  const column = (deg: number, r: number, y0: number, y1: number, thick: number) => {
    const t = (deg * Math.PI) / 180
    cylinder(Vector3.create(PLAZA.x + Math.sin(t) * r, (y0 + y1) / 2, PLAZA.z + Math.cos(t) * r), Vector3.create(thick, y1 - y0, thick), PALETTE.column, true)
  }
  // ground: between the corners, two flanking the entrance path; game room: between its corners
  for (const deg of [160, 200, 259, 304, 0, 56, 101]) column(deg, 11.4, 0, 8, 0.6)
  for (const deg of [45, 225, 315]) column(deg, 9.9, 8, 16, 0.5) // none in the SE quadrant: that is the elevator landing

  for (const f of FLOORS) elevatorPad(f)

  // game room (floor 1): lamps between the corners, planters at the oculus edge
  const y1 = FLOORS[1].y
  for (const deg of [45, 165, 225, 315]) {
    const t = (deg * Math.PI) / 180
    lamp(PLAZA.x + Math.sin(t) * 7.4, PLAZA.z + Math.cos(t) * 7.4, y1)
  }
  for (const deg of [22, 68, 112, 158, 202, 248, 292, 338]) {
    const t = (deg * Math.PI) / 180
    planter(PLAZA.x + Math.sin(t) * 6.4, PLAZA.z + Math.cos(t) * 6.4, y1)
  }
  label(Vector3.create(PLAZA.x, y1 + 3.2, PLAZA.z + 5.2), 'GAME ROOM', 2.6, Color4.White(), 8)

  // rooftop terrace (floor 2): benches looking down the oculus, lamps, a sign
  const y2 = FLOORS[2].y
  const roofCentre = Vector3.create(PLAZA.x, y2, PLAZA.z)
  for (const deg of [30, 100, 170, 260, 330]) {
    const t = (deg * Math.PI) / 180
    bench(Vector3.create(PLAZA.x + Math.sin(t) * 6.4, y2, PLAZA.z + Math.cos(t) * 6.4), roofCentre)
  }
  for (const deg of [60, 130, 210, 300]) {
    const t = (deg * Math.PI) / 180
    lamp(PLAZA.x + Math.sin(t) * 9.2, PLAZA.z + Math.cos(t) * 9.2, y2)
  }
  planter(PLAZA.x - 8.6, PLAZA.z + 3, y2)
  planter(PLAZA.x + 8.6, PLAZA.z + 3, y2)
  label(Vector3.create(PLAZA.x, y2 + 3.4, PLAZA.z + 7.5), 'ROOFTOP', 2.6, Color4.White(), 8)
  label(Vector3.create(PLAZA.x, y2 + 2.2, PLAZA.z + 7.5), 'Leaderboard and tournaments: coming after the buildathon', 1.1, PALETTE.cream, 10)
}
