/**
 * The lounge itself: a garden ring, the fenced parquet lounge with its round
 * plaza (info kiosk, welcome sign, benches) and one "corner" per game with a
 * tinted rug, a banner pole and planters as dividers; above it the twisted
 * tower (models/tower.glb, generated by tools/gen-tower.py) with the game
 * room and the rooftop terrace, reached by the elevator pads. Everything else
 * is primitives, no downloads, mobile-cheap. Tables are built by table3d on
 * top of this.
 */
import {
  Billboard,
  BillboardMode,
  ColliderLayer,
  Entity,
  Font,
  GltfContainer,
  InputAction,
  LightSource,
  Material,
  MaterialTransparencyMode,
  MeshCollider,
  MeshRenderer,
  TextAlignMode,
  TextShape,
  TextureWrapMode,
  Transform,
  engine,
  pointerEventsSystem
} from '@dcl/sdk/ecs'
import { Color3, Color4, Quaternion, Vector3 } from '@dcl/sdk/math'
import { BUILT_GAMES, ELEVATORS, FLOORS, LIGHTS, LOUNGE_MAX, LOUNGE_MIN, LOUNGE_SIZE, PALETTE, PLAZA, SCENE_SIZE, SPAWN, ZONES, yawToward, type FloorDef, type ZoneDef, INTERIOR } from './config'
import { GAME_NAMES, getGame } from './games/registry'
import { localeInfo, t as L, uiLang } from './i18n'
import { local } from './tables'
import { board, leaderboardEnabled, leaderboardTicker } from './leaderboard'
import { openExternalUrl } from '~system/RestrictedActions'
import { feedbackEnabled } from './feedback'

/**
 * Text labels that follow the UI language: each entry re-renders its text
 * when the player picks another language (relabelSystem below).
 */
const liveLabels: Array<{ entity: Entity; text: () => string }> = []
let labelledLang = ''
function liveLabel(pos: Vector3, text: () => string, fontSize: number, color = Color4.White(), width = 8): Entity {
  const e = label(pos, text(), fontSize, color, width)
  liveLabels.push({ entity: e, text })
  return e
}
export function relabelSystem(): void {
  if (uiLang.code === labelledLang) return
  labelledLang = uiLang.code
  for (const l of liveLabels) TextShape.getMutable(l.entity).text = l.text()
}

// ---------------------------------------------------------------- primitives

function solid(pos: Vector3, scale: Vector3, color: Color4, opts: { collide?: boolean; rotY?: number; parent?: Entity } = {}): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale, rotation: Quaternion.fromEulerDegrees(0, opts.rotY ?? 0, 0), parent: opts.parent })
  MeshRenderer.setBox(e)
  if (opts.collide) MeshCollider.setBox(e)
  Material.setPbrMaterial(e, { albedoColor: color, roughness: 0.9, metallic: 0 })
  return e
}

const PALACE = INTERIOR === 'palace'

function cylinder(pos: Vector3, scale: Vector3, color: Color4, collide = false): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale })
  MeshRenderer.setCylinder(e, 0.5, 0.5)
  if (collide) MeshCollider.setCylinder(e, 0.5, 0.5)
  Material.setPbrMaterial(e, { albedoColor: color, roughness: 0.9, metallic: 0 })
  return e
}

/** A structural column: fluted marble with gold capital and base in the palace finish, plain wood-brown otherwise. */
function column(pos: Vector3, scale: Vector3, collide = true): Entity {
  if (!PALACE) return cylinder(pos, scale, PALETTE.column, collide)
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale })
  MeshRenderer.setCylinder(e, 0.5, 0.5)
  if (collide) MeshCollider.setCylinder(e, 0.5, 0.5)
  // the shaft texture runs bottom -> top once (capital at v = 1); the cylinder's u wraps around
  const shaft = Material.Texture.Common({ src: 'models/palace/column.png', wrapMode: TextureWrapMode.TWM_CLAMP })
  Material.setPbrMaterial(e, { texture: shaft, albedoColor: Color4.White(), roughness: 0.4, metallic: 0, emissiveTexture: shaft, emissiveColor: Color3.create(1, 0.97, 0.92), emissiveIntensity: 0.18 })
  return e
}

function texturedBox(pos: Vector3, scale: Vector3, src: string, tiling: [number, number], collide = false, rotY = 0, selfLit = 0): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, scale, rotation: Quaternion.fromEulerDegrees(0, rotY, 0) })
  MeshRenderer.setBox(e)
  if (collide) MeshCollider.setBox(e)
  const tex = Material.Texture.Common({ src, wrapMode: TextureWrapMode.TWM_REPEAT, tiling: { x: tiling[0], y: tiling[1] } })
  Material.setPbrMaterial(e, {
    texture: tex,
    roughness: 0.85,
    metallic: 0,
    ...(selfLit > 0 ? { emissiveTexture: tex, emissiveColor: Color3.create(1, 0.97, 0.92), emissiveIntensity: selfLit } : {})
  })
  return e
}

/**
 * Round rug: the neutral rug texture tinted by `tint`, lying flat, with a
 * glowing edge ring in `glow` (emissive mask images/rug-ring.png) so every
 * game corner reads from a distance without an extra entity.
 */
export function rug(pos: Vector3, size: number, tint: Color4, y = 0.012, glow?: Color4): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(pos.x, y, pos.z), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(size, size, 1) })
  MeshRenderer.setPlane(e)
  // Palace: every zone gets the same royal round carpet (red velvet, gold border) so the marble
  // floors stay coherent; lounge: the neutral weave tinted per zone. Both glow softly on their own:
  // scene lights never reach the slab corners and the mobile client renders no lights at all.
  const g = glow ?? tint
  const weave = Material.Texture.Common({ src: PALACE ? 'models/palace/rug.png' : 'images/rug.png' })
  Material.setPbrMaterial(e, {
    texture: weave,
    albedoColor: PALACE ? Color4.White() : tint,
    emissiveTexture: weave,
    emissiveColor: PALACE ? Color3.create(1, 0.9, 0.85) : Color3.create((tint.r + g.r) / 2, (tint.g + g.g) / 2, (tint.b + g.b) / 2),
    emissiveIntensity: PALACE ? 0.28 : 0.5,
    transparencyMode: MaterialTransparencyMode.MTM_ALPHA_TEST,
    alphaTest: 0.5,
    roughness: 1,
    metallic: 0,
    castShadows: false
  })
  return e
}

function label(pos: Vector3, text: string, fontSize: number, color = Color4.White(), width = 8): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos })
  TextShape.create(e, {
    text,
    fontSize,
    font: Font.F_SANS_SERIF,
    textAlign: TextAlignMode.TAM_MIDDLE_CENTER,
    textColor: color,
    outlineWidth: 0.2,
    outlineColor: Color3.Black(),
    width,
    height: 2
  })
  Billboard.create(e, { billboardMode: BillboardMode.BM_Y })
  return e
}

// ---------------------------------------------------------------- furniture

/**
 * Prop instance: one entity with a shared GLB (models/*.glb from
 * tools/gen-models.py). Every prop used to be two to six primitives with a
 * material each; as instances they share mesh and materials, which is what
 * keeps the phone's material count in budget.
 */
function prop(src: string, pos: Vector3, rotY = 0, scale = 1, collide = false): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, rotation: Quaternion.fromEulerDegrees(0, rotY, 0), scale: Vector3.create(scale, scale, scale) })
  GltfContainer.create(e, { src, visibleMeshesCollisionMask: collide ? ColliderLayer.CL_PHYSICS : ColliderLayer.CL_NONE, invisibleMeshesCollisionMask: ColliderLayer.CL_PHYSICS })
  return e
}

function planter(x: number, z: number, y = 0): void {
  prop(finish('planter'), Vector3.create(x, y, z), 0, 1, true)
}

/** Garden tree (trunk + two leaf balls), `size` scales the whole tree. */
function tree(x: number, z: number, size = 1): void {
  prop('models/tree.glb', Vector3.create(x, 0, z), (x * 37 + z * 11) % 360, size, true)
}

function lamp(x: number, z: number, y = 0): void {
  prop(finish('lamp'), Vector3.create(x, y, z), 45)
}

/** A bench facing `toward` (models/bench.glb). */
function bench(pos: Vector3, toward: Vector3): void {
  prop(finish('bench'), pos, yawToward(pos, toward), 1, true)
}
/** Model path of a lounge prop in the current finish (every prop below has a marble + brass palace variant). */
function finish(name: 'sofa' | 'bar' | 'bench' | 'board' | 'kiosk' | 'shaft' | 'gateway' | 'lamp' | 'planter' | 'plazatree'): string {
  return PALACE ? `models/${name}-palace.glb` : `models/${name}.glb`
}

/**
 * Walkable ring path around a floor's centre: a light carpet runner (alpha-cut plane
 * textured with a ring) that furniture keeps off. `outer` is the ring's outer radius;
 * the inner radius comes from the texture (path-a 0.786, path-b 0.654 of outer).
 */
function pathRing(y: number, outer: number, tex: string): Entity {
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(PLAZA.x, y + 0.006, PLAZA.z), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(outer * 2, outer * 2, 1) })
  MeshRenderer.setPlane(e)
  // a touch of self-light keeps the runner readable under the purple night sky; the palace textures
  // carry their own red velvet + gold borders, the lounge's cream texture is used untinted
  const glow = PALACE ? Color3.create(1, 0.9, 0.85) : Color3.create(1, 0.96, 0.9)
  Material.setPbrMaterial(e, { texture: Material.Texture.Common({ src: tex }), roughness: 1, metallic: 0, castShadows: false, transparencyMode: MaterialTransparencyMode.MTM_ALPHA_TEST, alphaTest: 0.5, emissiveTexture: Material.Texture.Common({ src: tex }), emissiveColor: glow, emissiveIntensity: PALACE ? 0.16 : 0.22 })
  return e
}

/** Banner pole with a coloured cloth and the game name, marking a corner. */
function zoneBanner(z: ZoneDef): void {
  // pole stands on the outer side of the corner (away from the plaza)
  const y = z.position.y
  const centre = Vector3.create(PLAZA.x, y, PLAZA.z)
  const away = Vector3.normalize(Vector3.subtract(z.position, centre))
  // a lone four-seat table has seat pads on BOTH local axes at 1.8 m, so an on-axis pole lands
  // exactly on the outer seat (players stood up into it); step diagonally between two pads instead
  const lone4 = z.tables === 1 && (getGame(z.gameId).seats ?? 2) > 2
  const dir = lone4 ? Vector3.rotate(away, Quaternion.fromEulerDegrees(0, -45, 0)) : away
  const pos = Vector3.add(z.position, Vector3.scale(dir, lone4 ? 2.3 : z.floor === 1 ? 1.8 : 2.6)) // floor 1: 2.6 put the pole in the railing
  cylinder(Vector3.create(pos.x, y + 1.7, pos.z), Vector3.create(0.12, 3.4, 0.12), PALACE ? PALETTE.brass : PALETTE.woodDark, true)
  const cloth = engine.addEntity()
  Transform.create(cloth, {
    position: Vector3.create(pos.x, y + 2.35, pos.z),
    rotation: Quaternion.fromEulerDegrees(0, yawToward(pos, centre), 0),
    scale: Vector3.create(0.9, 1.7, 1)
  })
  MeshRenderer.setPlane(cloth)
  Material.setPbrMaterial(cloth, { albedoColor: z.banner, roughness: 0.9, metallic: 0, castShadows: false })
  const built = BUILT_GAMES.includes(z.gameId)
  const name = () => localeInfo(uiLang.code).games[z.gameId]?.name ?? GAME_NAMES[z.gameId]
  // big billboard name high above the corner: readable from the entrance and from the other floors
  liveLabel(Vector3.create(pos.x, y + 5.4, pos.z), () => (built ? name() : `${name()}\n${L().comingSoon}`), built ? 3.4 : 2.2, Color4.White(), 12)
}

/**
 * Elevator shaft: four slim posts and translucent glass on the sides away
 * from the plaza run from the ground to above the rooftop, so the shaft reads
 * as one elevator from anywhere in the lounge; on every floor a glowing pad
 * (standing on it opens the floor panel, see tables.ts / ui.tsx), a light
 * ring and an ELEVATOR sign facing the plaza.
 */
function elevatorShaft(pad: Vector3): void {
  // models/shaft.glb: posts, glass on three sides (open towards -Z = the plaza), roof, pads + light rings on every floor
  const shaft = prop(finish('shaft'), Vector3.create(pad.x, 0, pad.z), yawToward(pad, PLAZA))
  for (const f of FLOORS) {
    liveLabel(Vector3.create(pad.x, f.y + 3.05, pad.z), () => L().elevator, 2.0, Color4.White(), 6)
    liveLabel(Vector3.create(pad.x, f.y + 2.35, pad.z), () => L().floors.join(' · '), 0.9, PALETTE.cream, 6)
    if (!PALACE) continue
    // parchment directory on the back wall of the cabin (local +Z), readable from inside on every floor
    const sign = engine.addEntity()
    Transform.create(sign, { parent: shaft, position: Vector3.create(0, f.y + 1.78, 1.17), scale: Vector3.create(1.9, 1.5, 1) })
    MeshRenderer.setPlane(sign)
    const parchment = Material.Texture.Common({ src: 'images/ui/panel-royal.png' })
    Material.setPbrMaterial(sign, { texture: parchment, roughness: 0.9, metallic: 0, castShadows: false, transparencyMode: MaterialTransparencyMode.MTM_ALPHA_TEST, alphaTest: 0.5, emissiveTexture: parchment, emissiveColor: Color3.create(1, 0.97, 0.9), emissiveIntensity: 0.35 })
    const txt = engine.addEntity()
    Transform.create(txt, { parent: shaft, position: Vector3.create(0, f.y + 1.78, 1.14) })
    TextShape.create(txt, { text: directoryText(), fontSize: 0.5, font: Font.F_SANS_SERIF, textAlign: TextAlignMode.TAM_MIDDLE_CENTER, textColor: Color4.fromHexString('#2b1d12ff'), width: 1.6, height: 1.3, textWrapping: true })
    liveLabels.push({ entity: txt, text: directoryText })
  }
}

/** Directory: which games are on which floor, in the UI language (models/board.glb + a live label). */
/** The directory text: every floor with its games, in the UI language. */
function directoryText(): string {
  const names = (floor: number) =>
    Array.from(new Set(ZONES.filter((zn) => zn.floor === floor && BUILT_GAMES.includes(zn.gameId)).map((zn) => zn.gameId)))
      .map((id) => localeInfo(uiLang.code).games[id]?.name ?? GAME_NAMES[id])
      .join(' · ')
  const f = L().floors
  return `${f[0].toUpperCase()}\n${names(0)}\n\n${f[1].toUpperCase()} ▲\n${names(1)}\n\n${f[2].toUpperCase()} ▲▲\n${names(2)}\n\n${f[3].toUpperCase()} ▲▲▲`
}

/**
 * Museum label for a floor's ceiling artwork (Arsalan 20 Aug): the directory stele model
 * with a static plate text naming the fresco, Pozzo and the photographer. Spots are
 * clash-checked against each floor's rugs, columns, shafts, runners, sofas and railings.
 */
function artworkBoard(pos: Vector3, yaw: number, text: string): void {
  const e = engine.addEntity()
  Transform.create(e, { position: pos, rotation: Quaternion.fromEulerDegrees(0, yaw, 0) })
  GltfContainer.create(e, { src: 'models/directory-palace.glb' })
  const lbl = engine.addEntity()
  // plate front sits at local z -0.155 (brass inlay -0.151): the label floats just proud
  Transform.create(lbl, { parent: e, position: Vector3.create(0, 1.83, -0.16) })
  TextShape.create(lbl, { text, fontSize: 0.34, font: Font.F_SANS_SERIF, textAlign: TextAlignMode.TAM_MIDDLE_CENTER, textColor: PALETTE.cream, width: 1.02, height: 1.45, textWrapping: true })
}

function directoryBoard(x: number, z: number): void {
  // palace: one marble stele with the plate on its front (-Z); on the left of the entrance the front
  // turns east towards the path (yaw 270); lounge: the framed board on a post, plate symmetric
  const yaw = PALACE ? 270 : 90
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(x, PALACE ? 0 : 2.2, z), rotation: Quaternion.fromEulerDegrees(0, yaw, 0) })
  GltfContainer.create(e, { src: PALACE ? 'models/directory-palace.glb' : 'models/board.glb' })
  const text = directoryText
  const lbl = engine.addEntity()
  // text shapes read from their -Z side: yaw 270 faces east (the lounge board plate sits at yaw 90, so its label is turned round)
  Transform.create(lbl, { position: Vector3.create(x + (PALACE ? 0.175 : 0.06), PALACE ? 1.83 : 2.2, z), rotation: Quaternion.fromEulerDegrees(0, 270, 0) })
  TextShape.create(lbl, { text: text(), fontSize: PALACE ? 0.46 : 0.95, font: Font.F_SANS_SERIF, textAlign: TextAlignMode.TAM_MIDDLE_CENTER, textColor: PALETTE.cream, width: PALACE ? 1.05 : 2.4, height: PALACE ? 1.5 : 1.8, textWrapping: true })
  liveLabels.push({ entity: lbl, text })
}

/**
 * Welcome stele left of the entrance (palace): the host's portrait, a greeting, credits and a
 * GL & HF; tapping it opens the builder's profile page. Landscape sibling of the directory stele.
 */
function welcomeBoard(x: number, z: number): void {
  const e = engine.addEntity()
  // right of the entrance: front (-Z local) turns west towards the path with yaw 90
  Transform.create(e, { position: Vector3.create(x, 0, z), rotation: Quaternion.fromEulerDegrees(0, 90, 0) })
  GltfContainer.create(e, { src: 'models/welcome-palace.glb' })
  // portrait on the viewer's left (local +X with yaw 90); plate centre y 1.565, 2.25 x 1.35;
  // the plane's unmirrored face is +Z, so it turns 180 to show correctly on the front
  const pic = engine.addEntity()
  Transform.create(pic, { parent: e, position: Vector3.create(0.72, 1.565, -0.155), rotation: Quaternion.fromEulerDegrees(0, 180, 0), scale: Vector3.create(0.72, 1.17, 1) })
  MeshRenderer.setPlane(pic)
  const host = Material.Texture.Common({ src: 'images/host.jpg' })
  Material.setPbrMaterial(pic, { texture: host, roughness: 0.9, metallic: 0, castShadows: false, emissiveTexture: host, emissiveColor: Color3.create(1, 1, 1), emissiveIntensity: 0.3 })
  const txt = engine.addEntity()
  Transform.create(txt, { parent: e, position: Vector3.create(-0.38, 1.565, -0.16) })
  TextShape.create(txt, {
    text: 'Hi, welcome to Arena Lounge!\n\nBuilt with love by <b>ArsalanRC</b>\nArsalanRC.dcl.eth\n\n<b>GL & HF!</b>\n\n<i>Tap the board for my profile</i>',
    fontSize: 0.62,
    font: Font.F_SANS_SERIF,
    textAlign: TextAlignMode.TAM_MIDDLE_CENTER,
    textColor: PALETTE.cream,
    width: 1.4,
    height: 1.3,
    textWrapping: true
  })
  pointerEventsSystem.onPointerDown({ entity: e, opts: { button: InputAction.IA_POINTER, hoverText: 'ArsalanRC', maxDistance: 12 } }, () => {
    void openExternalUrl({ url: 'https://arsalanrc.github.io' })
  })
  // museum label on the stele base: the ceiling artworks' visible credit (details in
  // models/palace/CREDITS.md; Arsalan asked 20 Aug where the artist is credited in-world)
  // y 0.71 / z -0.165: the only clear band on the front. The octagonal base courses reach
  // 0.72 m forward below y 0.58 (a label there sits INSIDE the marble, invisible), the brass
  // inlay line crosses at y 0.84, and the body face itself is at z -0.15.
  const credit = engine.addEntity()
  Transform.create(credit, { parent: e, position: Vector3.create(0, 0.71, -0.165) })
  TextShape.create(credit, {
    text: 'Ceilings: Andrea Pozzo · Sant\'Ignazio, Rome & Jesuit Church, Vienna\nPhotos: Wilfredor CC0 · J.-C. BENOIST CC BY 2.5 · Everbruin CC BY-SA 4.0',
    fontSize: 0.2,
    font: Font.F_SANS_SERIF,
    textAlign: TextAlignMode.TAM_MIDDLE_CENTER,
    textColor: PALETTE.cream,
    width: 2.5,
    height: 0.3,
    textWrapping: true
  })
}

/** A post with a glowing "?" cube: tap to open How to play. */
function infoKiosk(x: number, z: number): void {
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(x, 0, z), rotation: Quaternion.fromEulerDegrees(0, 45, 0) })
  GltfContainer.create(e, { src: finish('kiosk'), invisibleMeshesCollisionMask: ColliderLayer.CL_POINTER, visibleMeshesCollisionMask: ColliderLayer.CL_NONE })
  label(Vector3.create(x, 1.45, z), '?', 4, Color4.White(), 2)
  liveLabel(Vector3.create(x, 2.05, z), () => L().howToPlay, 1.4, Color4.White(), 4)
  pointerEventsSystem.onPointerDown({ entity: e, opts: { button: InputAction.IA_POINTER, hoverText: 'How to play', maxDistance: 10 } }, () => {
    local.helpOpen = true
  })
}

/**
 * Suggestion box (ideas + bugs) beside the entrance: a brass letter box on a
 * marble pedestal (models/postbox.glb); clicking it opens the feedback panel.
 */
function feedbackBox(x: number, z: number): void {
  if (!feedbackEnabled()) return
  const e = engine.addEntity()
  Transform.create(e, { position: Vector3.create(x, 0, z), rotation: Quaternion.fromEulerDegrees(0, -45, 0) })
  GltfContainer.create(e, { src: 'models/postbox.glb', invisibleMeshesCollisionMask: ColliderLayer.CL_POINTER, visibleMeshesCollisionMask: ColliderLayer.CL_NONE })
  liveLabel(Vector3.create(x, 2.05, z), () => L().feedbackSign, 1.1, PALETTE.brass, 4)
  pointerEventsSystem.onPointerDown({ entity: e, opts: { button: InputAction.IA_POINTER, hoverText: 'Ideas & bugs', maxDistance: 10 } }, () => {
    local.feedbackOpen = true
    local.feedbackState = 'idle'
  })
}

// ---------------------------------------------------------------- scene

export function buildLounge(): void {
  const half = SCENE_SIZE / 2
  const lc = LOUNGE_MIN + LOUNGE_SIZE / 2 // lounge centre (x and z)

  // ground: one collider slab under the whole scene, lawn on top, parquet on the lounge
  solid(Vector3.create(half, -0.05, half), Vector3.create(SCENE_SIZE, 0.1, SCENE_SIZE), PALETTE.floor, { collide: true })
  const lawn = engine.addEntity()
  Transform.create(lawn, { position: Vector3.create(half, 0.001, half), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(SCENE_SIZE, SCENE_SIZE, 1) })
  MeshRenderer.setPlane(lawn)
  Material.setPbrMaterial(lawn, { albedoColor: PALETTE.lawn, roughness: 1, metallic: 0, castShadows: false })
  const parquet = engine.addEntity()
  Transform.create(parquet, { position: Vector3.create(lc, 0.003, lc), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(LOUNGE_SIZE, LOUNGE_SIZE, 1) })
  MeshRenderer.setPlane(parquet)
  // palace: marble tiles on a 4 m repeat (2 m tiles); lounge: dark parquet
  const floorTex = Material.Texture.Common({ src: PALACE ? 'models/palace/floor.png' : 'images/floor.png', wrapMode: TextureWrapMode.TWM_REPEAT, tiling: PALACE ? { x: LOUNGE_SIZE / 4, y: LOUNGE_SIZE / 4 } : { x: 10, y: 10 } })
  Material.setPbrMaterial(parquet, {
    texture: floorTex,
    roughness: PALACE ? 0.35 : 0.75,
    metallic: 0,
    castShadows: false,
    // palace marble keeps a little of its own light so the purple night ambient does not turn it lavender
    ...(PALACE ? { emissiveTexture: floorTex, emissiveColor: Color3.create(1, 0.97, 0.92), emissiveIntensity: 0.18 } : {})
  })

  // low wooden boundary around the lounge so nobody walks off the parquet on a
  // phone, with a cap rail; the entrance gap is in the south wall
  const wallH = 0.9
  const wallT = 0.3
  const gap = 4.2 // entrance width, centred on the spawn
  const west = LOUNGE_MIN + (SPAWN.x - gap / 2 - LOUNGE_MIN) / 2
  const east = SPAWN.x + gap / 2 + (LOUNGE_MAX - SPAWN.x - gap / 2) / 2
  const wLen = SPAWN.x - gap / 2 - LOUNGE_MIN
  const eLen = LOUNGE_MAX - SPAWN.x - gap / 2
  // palace: marble panels (2:1, engraved frieze along the top) with a brass cap rail; lounge: wood
  const wallTex = PALACE ? 'models/palace/wall.png' : 'images/wood.png'
  const panels = (len: number): [number, number] => (PALACE ? [Math.max(1, Math.round(len / (wallH * 2))), 1] : [len < 10 ? 3.5 : 8, 1])
  const rail = PALACE ? PALETTE.brass : PALETTE.woodDark
  const lit = PALACE ? 0.16 : 0
  texturedBox(Vector3.create(west, wallH / 2, LOUNGE_MIN + wallT / 2), Vector3.create(wLen, wallH, wallT), wallTex, panels(wLen), true, 0, lit)
  texturedBox(Vector3.create(east, wallH / 2, LOUNGE_MIN + wallT / 2), Vector3.create(eLen, wallH, wallT), wallTex, panels(eLen), true, 0, lit)
  texturedBox(Vector3.create(lc, wallH / 2, LOUNGE_MAX - wallT / 2), Vector3.create(LOUNGE_SIZE, wallH, wallT), wallTex, panels(LOUNGE_SIZE), true, 0, lit)
  texturedBox(Vector3.create(LOUNGE_MIN + wallT / 2, wallH / 2, lc), Vector3.create(LOUNGE_SIZE, wallH, wallT), wallTex, panels(LOUNGE_SIZE), true, 90, lit)
  texturedBox(Vector3.create(LOUNGE_MAX - wallT / 2, wallH / 2, lc), Vector3.create(LOUNGE_SIZE, wallH, wallT), wallTex, panels(LOUNGE_SIZE), true, 90, lit)
  solid(Vector3.create(west, wallH + 0.03, LOUNGE_MIN + wallT / 2), Vector3.create(wLen, 0.06, wallT + 0.1), rail)
  solid(Vector3.create(east, wallH + 0.03, LOUNGE_MIN + wallT / 2), Vector3.create(eLen, 0.06, wallT + 0.1), rail)
  solid(Vector3.create(lc, wallH + 0.03, LOUNGE_MAX - wallT / 2), Vector3.create(LOUNGE_SIZE, 0.06, wallT + 0.1), rail)
  solid(Vector3.create(LOUNGE_MIN + wallT / 2, wallH + 0.03, lc), Vector3.create(wallT + 0.1, 0.06, LOUNGE_SIZE), rail)
  solid(Vector3.create(LOUNGE_MAX - wallT / 2, wallH + 0.03, lc), Vector3.create(wallT + 0.1, 0.06, LOUNGE_SIZE), rail)

  // garden ring outside the fence: a path from the scene edge to the entrance,
  // trees and lamps, and the scene edge kept walkable-safe by the fence itself
  const path = engine.addEntity()
  Transform.create(path, { position: Vector3.create(SPAWN.x, 0.002, LOUNGE_MIN / 2), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(gap, LOUNGE_MIN, 1) })
  MeshRenderer.setPlane(path)
  Material.setPbrMaterial(path, { albedoColor: PALETTE.path, roughness: 1, metallic: 0, castShadows: false })
  for (const [x, z, sz] of [[4, 4, 1.1], [4, 44, 1.0], [44, 4, 1.15], [44, 44, 1.05], [4, 24, 0.9], [44, 24, 0.95], [24, 44.5, 1.1], [13, 3.5, 0.85], [35, 3.5, 0.9], [4, 14, 0.8], [44, 34, 0.8]]) {
    tree(x, z, sz)
  }
  for (const [x, z] of [[SPAWN.x - 3, 3], [SPAWN.x + 3, 3], [3, 40], [45, 40], [3, 8], [45, 8]]) lamp(x, z)

  // the plaza: a big warm rug, a tree in the middle as the landmark, four
  // benches facing in, lamps at the corners
  rug(PLAZA, 9.5, Color4.fromHexString('#e3c9a3ff'), 0.008, Color4.fromHexString('#ffd27aff'))
  // plaza centre: in the palace a Roman three-tier marble fountain; in the lounge the potted tree
  if (PALACE) prop('models/statue-palace.glb', Vector3.create(PLAZA.x, 0, PLAZA.z), 0, 1, true)
  else prop('models/plazatree.glb', Vector3.create(PLAZA.x, 0, PLAZA.z), 0, 1, true)
  for (const [x, z] of [[PLAZA.x - 3.6, PLAZA.z + 2.6], [PLAZA.x + 3.6, PLAZA.z + 2.6], [PLAZA.x - 3.6, PLAZA.z - 2.6], [PLAZA.x + 3.6, PLAZA.z - 2.6]]) {
    bench(Vector3.create(x, 0, z), PLAZA)
  }
  lamp(PLAZA.x, PLAZA.z + 7)
  lamp(PLAZA.x - 6.5, PLAZA.z)
  lamp(PLAZA.x + 6.5, PLAZA.z)

  // corners on every floor: rug + banner (planters between ground-floor neighbours)
  for (const z of ZONES) {
    // upper floors get tighter rugs (the annular slabs need a walkway inside and outside the
    // tables), except under a four-seat table, which needs room on every side
    const fourSeats = (getGame(z.gameId).seats ?? 2) > 2
    // rug sizes keep clear of the walking ring inside the seats: 6.8 m for a ground pair, 5.4 m for a pair on a slab
    if (BUILT_GAMES.includes(z.gameId)) rug(z.position, z.tables > 1 ? (z.floor > 0 ? 5.4 : 6.8) : z.floor > 0 && !fourSeats ? 4.4 : 5.6, z.rug, z.position.y + 0.012, z.banner)
    zoneBanner(z)
  }
  const ground = ZONES.filter((z) => z.floor === 0)
  for (let i = 0; i < ground.length; i++) {
    const a = ground[i].position
    const b = ground[(i + 1) % ground.length].position
    // skip the gap between the two southern corners: that is the entrance
    if (Vector3.distance(a, b) > 14) continue
    const mid = Vector3.scale(Vector3.add(a, b), 0.5)
    const away = Vector3.normalize(Vector3.subtract(mid, PLAZA))
    const p = Vector3.add(mid, Vector3.scale(away, 1.2))
    if (ELEVATORS.some((e) => Vector3.distance(Vector3.create(e.x, 0, e.z), p) < 2.6)) continue
    planter(p.x, p.z)
  }
  planter(LOUNGE_MIN + 2.6, LOUNGE_MIN + 2.6)
  planter(LOUNGE_MAX - 2.6, LOUNGE_MIN + 2.6)
  planter(LOUNGE_MIN + 2.6, LOUNGE_MAX - 2.6)
  planter(LOUNGE_MAX - 2.6, LOUNGE_MAX - 2.6)

  // entrance sequence (south to north): portal, bars flanking the path, gateway with the
  // welcome sign, then the ring path; kiosk and directory sit off the path to the west
  const gz = PLAZA.z - 8.6
  // palace: no gateway frame; the carpet, the two steles and the marquee carry the entrance (his call, 20 Aug)
  if (!PALACE) prop(finish('gateway'), Vector3.create(SPAWN.x, 0, gz), 0, 1, true)
  liveLabel(Vector3.create(SPAWN.x, 4.2, gz), () => L().welcome, 1.6, PALETTE.cream, 12)
  infoKiosk(20.3, 16.0)
  feedbackBox(27.0, 15.4) // clear of the east elevator shaft
  directoryBoard(21.4, 11.9) // left of the entrance (mirrors the welcome stele); lounge: on the left bar

  // one ceiling-credit board per artwork floor (rooftop is open sky). Ground: entrance court
  // west of the path, faces east like the directory (2.4 m off the kiosk, 6 m off the nearest
  // rug). Game room: free arc between Croc Snap and Snakes & Ladders (3.7 m off the rug, 1.4 m
  // off the 202.5-deg column). Sky room: between the west sofa and Dice Royale (4.3 m / 2.5 m).
  if (PALACE) {
    artworkBoard(Vector3.create(18.4, 0, 14.6), 270, "THE CEILING\n\nTriumph of St Ignatius\nAndrea Pozzo, 1685-94\nSant'Ignazio, Rome\n\nPhoto: Wilfredor (CC0)")
    const g = Vector3.create(20.27, FLOORS[1].y, 13.76)
    artworkBoard(g, yawToward(g, PLAZA), 'THE CEILING\n\nVault fresco\nAndrea Pozzo, 1703\nJesuit Church, Vienna\n\nPhoto: Everbruin\n(CC BY-SA 4.0)')
    const sk = Vector3.create(16.55, FLOORS[2].y, 19.7)
    artworkBoard(sk, yawToward(sk, PLAZA), "THE CEILING\n\nThe painted dome\nAndrea Pozzo, 1685\nSant'Ignazio, Rome\n\nPhoto: J.-C. BENOIST\n(CC BY 2.5)")
  }

  buildTower()

  // real lights on top of the emissive fixtures (see config LIGHTS)
  for (const l of LIGHTS) {
    const e = engine.addEntity()
    Transform.create(e, { position: Vector3.create(l.x, l.y, l.z) })
    LightSource.create(e, { type: LightSource.Type.Point({}), color: l.color, intensity: l.intensity, range: l.range, shadow: false })
  }
}

/**
 * The twisted tower: one GLB for ribs, slabs, railings and their colliders
 * (tools/gen-tower.py), plus primitive columns, the elevator pads and the
 * furniture of the game room and the rooftop terrace.
 */
function buildTower(): void {
  const tower = engine.addEntity()
  Transform.create(tower, { position: Vector3.create(PLAZA.x, 0, PLAZA.z) })
  GltfContainer.create(tower, { src: PALACE ? 'models/tower-palace.glb' : 'models/tower.glb' })
  // glass facade with the entrance portal, string lights (models/decor.glb, same origin)
  const decor = engine.addEntity()
  Transform.create(decor, { position: Vector3.create(PLAZA.x, 0, PLAZA.z) })
  GltfContainer.create(decor, { src: 'models/decor.glb', visibleMeshesCollisionMask: ColliderLayer.CL_NONE, invisibleMeshesCollisionMask: ColliderLayer.CL_PHYSICS })
  // the name over the portal is baked neon geometry in decor.glb (tools/gen-models.py)

  // lounge furniture: sofa pairs close to the plaza tree (inside the ring path), two bars
  // flanking the entrance path just inside the portal
  for (const deg of [22, 158, 202, 338]) {
    const t = (deg * Math.PI) / 180
    // 0.015 lift: the sofa base is coplanar with the floor and z-fights on bare marble (sky room pair)
    const pos = Vector3.create(PLAZA.x + Math.sin(t) * 4.6, 0.015, PLAZA.z + Math.cos(t) * 4.6)
    prop(finish('sofa'), pos, yawToward(pos, PLAZA) + 180, 1, true)
  }
  if (!PALACE) {
    prop(finish('bar'), Vector3.create(21.4, 0, 11.9), 90, 1, true)
    prop(finish('bar'), Vector3.create(26.6, 0, 11.9), -90, 1, true)
  } else {
    welcomeBoard(26.6, 11.9) // right of the entrance: the host's welcome stele
  }

  // the walkable ring on every floor: one alpha-cut runner plane each, clear of furniture and seats,
  // 2 m+ wide (ratio 0.705: ground 5.4..7.6, game room 5.2..7.4, rooftop 4.65..6.6; 0.60: sky room 3.4..5.7).
  // Palace: red velvet with gold border bands baked in; lounge: the cream runners, tinted in pathRing
  const ringA = PALACE ? 'models/palace/runner-a.png' : 'images/path-a.png'
  const ringB = PALACE ? 'models/palace/runner-b.png' : 'images/path-b.png'
  pathRing(FLOORS[0].y, 7.6, ringA)
  pathRing(FLOORS[1].y, 7.4, ringA)
  pathRing(FLOORS[2].y, 5.7, ringB)
  pathRing(FLOORS[3].y, 6.6, ringA)
  if (PALACE) {
    // straight entrance carpet: from the fence gap up into the ring band, same velvet + gold edges
    const carpet = engine.addEntity()
    const z0 = 6.4 // the fence line is at z 8.15: reach well onto the garden path so arrivals step onto it earlier (was 7.6; Arsalan 20 Aug)
    const z1 = PLAZA.z - 6.4 // reaches into the ring band (16.4 .. 18.6), the ring draws above it
    Transform.create(carpet, { position: Vector3.create(SPAWN.x, 0.005, (z0 + z1) / 2), rotation: Quaternion.fromEulerDegrees(90, 0, 0), scale: Vector3.create(2.6, z1 - z0, 1) })
    MeshRenderer.setPlane(carpet)
    const ct = Material.Texture.Common({ src: 'models/palace/runner-s.png' })
    Material.setPbrMaterial(carpet, { texture: ct, roughness: 1, metallic: 0, castShadows: false, transparencyMode: MaterialTransparencyMode.MTM_ALPHA_TEST, alphaTest: 0.5, emissiveTexture: ct, emissiveColor: Color3.create(1, 0.9, 0.85), emissiveIntensity: 0.16 })
  }

  // columns carrying the slabs, between the corners so they never block a table
  const columnAt = (deg: number, r: number, y0: number, y1: number, thick: number) => {
    const t = (deg * Math.PI) / 180
    column(Vector3.create(PLAZA.x + Math.sin(t) * r, (y0 + y1) / 2, PLAZA.z + Math.cos(t) * r), Vector3.create(thick, y1 - y0, thick), true)
  }
  // ground: between the corners, two flanking the entrance path; game room: between its corners
  // r 12.6 / 12.2: the two-table zones reach further out than the old single tables; at 11.4/10.4 the
  // columns stood in the outer seat pads (walkthrough 20 Aug)
  for (const deg of [160, 200, 262, 304, 0, 56, 101]) columnAt(deg, 12.6, 0, 8, 0.6)
  // game room: eight uniform columns on the 22.5° grid (clear of all six zones and both shafts)
  for (let k = 0; k < 8; k++) columnAt(22.5 + k * 45, 12.2, 8, 16, 0.5) // between the game-room corners, clear of both elevators and of the walkways

  for (const pad of ELEVATORS) elevatorShaft(pad)

  // game room (floor 1): the ring stays clear so people can walk around it (no planters here)
  const y1 = FLOORS[1].y
  liveLabel(Vector3.create(PLAZA.x, y1 + 3.2, PLAZA.z + 5.2), () => L().gameRoom, 2.6, Color4.White(), 8)

  // sky room (floor 2): two game corners (N, S), sofas at E and W looking over the oculus, planters, lamps
  const y2 = FLOORS[2].y
  for (const deg of [45, 120, 225]) columnAt(deg, 9.5, 16, 24, 0.5)
  for (const deg of [90, 270]) {
    const t = (deg * Math.PI) / 180
    const pos = Vector3.create(PLAZA.x + Math.sin(t) * 7.0, y2 + 0.015, PLAZA.z + Math.cos(t) * 7.0)
    prop(finish('sofa'), pos, yawToward(pos, PLAZA) + 180, 1, true)
  }
  liveLabel(Vector3.create(PLAZA.x, y2 + 3.2, PLAZA.z + 4.4), () => L().skyRoom, 2.6, Color4.White(), 8)

  // rooftop terrace (floor 3): benches looking down the oculus, planters, a sign under the crown
  const y3 = FLOORS[3].y
  const roofCentre = Vector3.create(PLAZA.x, y3, PLAZA.z)
  // benches look down the oculus; in the palace finish four marble pavilions stand between them
  for (const deg of PALACE ? [22, 90, 158, 202, 270, 338] : [30, 100, 170, 260, 330]) {
    const t = (deg * Math.PI) / 180
    bench(Vector3.create(PLAZA.x + Math.sin(t) * 7.2, y3, PLAZA.z + Math.cos(t) * 7.2), roofCentre)
  }
  if (PALACE) {
    // 45 and 225 only: the elevator shafts rise through this ring at ~142 and ~304 deg, and a
    // pavilion (half-diagonal ~2.1) needs 22+ deg of arc from each shaft AND each bench; the
    // two that stood at 135/315 interpenetrated the shafts (Arsalan, rooftop pass 20 Aug)
    for (const deg of [45, 225]) {
      const t = (deg * Math.PI) / 180
      // r 7.3: at 8.0 the pavilion corners (half-diagonal ~2.1) pierced the edge balustrade at r 9.95
      const pos = Vector3.create(PLAZA.x + Math.sin(t) * 7.3, y3, PLAZA.z + Math.cos(t) * 7.3)
      prop('models/pavilion.glb', pos, deg + 45, 1, true)
    }
  }
  planter(PLAZA.x - 8.3, PLAZA.z + 3, y3) // 8.9 pushed the leaf ball through the balustrade
  planter(PLAZA.x + 8.3, PLAZA.z + 3, y3)
  liveLabel(Vector3.create(PLAZA.x, y3 + 3.4, PLAZA.z - 7.0), () => L().rooftop, 2.6, Color4.White(), 8) // south, clear of the board
  if (leaderboardEnabled()) leaderboardBoard(Vector3.create(PLAZA.x, y3, PLAZA.z + 8.4))
  else liveLabel(Vector3.create(PLAZA.x, y3 + 2.2, PLAZA.z + 7.0), () => L().rooftopNote, 1.1, PALETTE.cream, 10)
}

/**
 * The rooftop leaderboard: the directory board model with the ranked rows as
 * monospace text, refreshed while somebody is on the rooftop (see
 * leaderboardSystem). Faces south (readers come from the elevators / oculus).
 */
function leaderboardBoard(pos: Vector3): void {
  // board.glb is a 2.6 x 1.9 plate on a 2.2 m pole; at 1.5x the plate is 3.9 x 2.85 with its
  // centre 2.6 m up. TextShapes read from their -Z side, and the readers stand south (-Z).
  prop(finish('board'), Vector3.create(pos.x, pos.y + 2.6, pos.z), 0, 1.5, true)
  const title = engine.addEntity()
  Transform.create(title, { position: Vector3.create(pos.x, pos.y + 3.72, pos.z - 0.14) })
  TextShape.create(title, { text: '', fontSize: 2.2, font: Font.F_SANS_SERIF, textAlign: TextAlignMode.TAM_MIDDLE_CENTER, textColor: PALETTE.cream, width: 3.6, height: 0.7, textWrapping: true })
  const body = engine.addEntity()
  Transform.create(body, { position: Vector3.create(pos.x, pos.y + 2.35, pos.z - 0.14) })
  // width 3.4 + wrapping: the plate is 3.9 wide, and the empty-state sentence used to run
  // straight past the frame (fontSize 1.35 monospace needs ~2x the plate for one line)
  TextShape.create(body, { text: '', fontSize: 1.15, font: Font.F_MONOSPACE, textAlign: TextAlignMode.TAM_MIDDLE_CENTER, textColor: Color4.White(), width: 3.4, height: 2.4, textWrapping: true })
  let shownVersion = -1
  let shownLang = ''
  engine.addSystem((dt) => {
    leaderboardTicker(dt, local.floor === 3)
    if (board.version === shownVersion && uiLang.code === shownLang) return
    shownVersion = board.version
    shownLang = uiLang.code
    const str = L()
    TextShape.getMutable(title).text = str.leaderboardTitle
    const rows = board.rows.slice(0, 10)
    TextShape.getMutable(body).text = rows.length === 0
      ? (board.failed ? str.leaderboardOffline : str.leaderboardEmpty)
      : rows.map((r) => `${String(r.rank).padStart(2, ' ')}. ${r.name.slice(0, 14).padEnd(14, ' ')} ${String(r.points).padStart(4, ' ')} ${str.pointsShort}`).join('\n')
  })
}
