/**
 * Screen-space UI: the mobile-first controller (game-agnostic part).
 *
 * On phones, tapping a 3D object means aiming the crosshair and pressing the
 * interaction button, which is slow for a board game. Screen UI is tapped
 * directly, so the UI is the controller and the 3D table is the shared show:
 *  - near a table:  card with the two seat buttons (no pad-hunting needed),
 *                   or the live board when both seats are taken (spectating)
 *  - seated:        the game's own controls (compact on phones) + status
 *  - always:        a top banner for onboarding / status and short toasts
 *
 * Visuals come from pre-shaded sprites in images/ui (generated by
 * tools/gen-textures.py) because mobile has no borderRadius / nine-slice;
 * every panel/button is a stretched rounded texture.
 *
 * React hooks are not available in React-ECS; the renderer runs every frame
 * and reads module state + synced components directly.
 */
import { Color4 } from '@dcl/sdk/math'
import ReactEcs, { ReactEcsRenderer, UiEntity, type UiTransformProps } from '@dcl/sdk/react-ecs'
import { isStateSyncronized } from '@dcl/sdk/network'
import { isMobile } from '@dcl/sdk/platform'
import { TURN_LIMIT_MS, UI } from './config'
import type { GameContext } from './games/types'
import { LOCALES, localeInfo, stringsFor } from './i18n'
import { SEAT_A, SEAT_B, Status, Winner, type Seat } from './state'
import {
  act,
  boardOf,
  dismissBot,
  findMySeat,
  gameStateOf,
  getTable,
  inviteBot,
  local,
  me,
  mySeatAt,
  otherSeat,
  rematch,
  seatOf,
  sit,
  sitWithBot,
  stand,
  type Table
} from './tables'

export function setupUi(): void {
  ReactEcsRenderer.setUiRenderer(LoungeUi, { virtualWidth: 1920, virtualHeight: 1080 })
}

// ---------------------------------------------------------------- assets

const IMG = {
  panel: 'images/ui/panel.png',
  pill: 'images/ui/pill.png',
  button: 'images/ui/button.png'
}
const WHITE = Color4.White()

type Margin = UiTransformProps['margin']
type Width = UiTransformProps['width']

function seatTint(seat: Seat): Color4 {
  return seat === SEAT_A ? UI.yellow : UI.red
}

// ---------------------------------------------------------------- atoms

function Btn(props: {
  label: string
  onClick: () => void
  color?: Color4
  textColor?: Color4
  width?: Width
  fontSize?: number
  margin?: Margin
}) {
  return (
    <UiEntity
      uiTransform={{
        width: props.width ?? 'auto',
        minWidth: typeof props.width === 'number' && props.width < 130 ? props.width : 130,
        height: 56,
        margin: props.margin ?? 5,
        padding: { left: 18, right: 18 },
        justifyContent: 'center',
        alignItems: 'center',
        pointerFilter: 'block'
      }}
      uiBackground={{ texture: { src: IMG.button }, textureMode: 'stretch', color: props.color ?? UI.accent }}
      uiText={{ value: props.label, fontSize: props.fontSize ?? 21, color: props.textColor ?? UI.text, textAlign: 'middle-center' }}
      onMouseDown={props.onClick}
    />
  )
}

/** Centred single line of text. Needs an explicit height: with height 'auto'
 *  the renderer ignores textAlign and draws the text top-left. */
function Text(props: { value: string; size?: number; color?: Color4; margin?: Margin; width?: Width }) {
  const size = props.size ?? 20
  return (
    <UiEntity
      uiTransform={{ width: props.width ?? '100%', height: Math.round(size * 1.45), margin: props.margin ?? 0, justifyContent: 'center', alignItems: 'center' }}
      uiText={{ value: props.value, fontSize: size, color: props.color ?? UI.text, textAlign: 'middle-center' }}
    />
  )
}

function Chip(props: { sprite: string; label: string; reverse?: boolean }) {
  const disc = (
    <UiEntity
      uiTransform={{ width: 26, height: 26, margin: props.reverse ? { left: 8 } : { right: 8 } }}
      uiBackground={{ texture: { src: props.sprite }, textureMode: 'stretch' }}
    />
  )
  const label = <UiEntity uiTransform={{ width: 'auto', height: 'auto' }} uiText={{ value: props.label, fontSize: 19, color: UI.text }} />
  return (
    <UiEntity uiTransform={{ width: 'auto', height: 30, flexDirection: 'row', alignItems: 'center' }}>
      {props.reverse ? label : disc}
      {props.reverse ? disc : label}
    </UiEntity>
  )
}

function Row(props: { children?: ReactEcs.JSX.Element | ReactEcs.JSX.Element[]; height?: number; margin?: Margin }) {
  return (
    <UiEntity uiTransform={{ width: '100%', height: props.height ?? 66, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', margin: props.margin ?? 0 }}>
      {props.children}
    </UiEntity>
  )
}

function secondsLeft(updatedAt: number): number {
  return Math.max(0, Math.ceil((TURN_LIMIT_MS - (Date.now() - updatedAt)) / 1000))
}

function contextFor(t: Table): GameContext {
  const mySeat = mySeatAt(t)
  const b = boardOf(t)
  return {
    root: t.root,
    mySeat,
    myTurn: mySeat !== 0 && b.status === Status.Playing && b.turn === mySeat,
    act: (action) => act(t, action)
  }
}

// ---------------------------------------------------------------- top banner

function bannerText(): string {
  if (!me.ready) return 'Loading your profile…'
  if (!isStateSyncronized() && !local.offline) return 'Connecting to the lounge…'
  if (findMySeat()) return ''
  if (!local.hasEverSat) return 'Walk up to a table and tap a seat to play'
  return ''
}

function Banner() {
  const text = bannerText()
  const toast = local.toast.until > Date.now() ? local.toast.text : ''
  const value = toast || text
  if (!value) return null
  return (
    <UiEntity
      uiTransform={{ positionType: 'absolute', position: { top: 18, left: '50%' }, margin: { left: -280 }, width: 560, height: 60, justifyContent: 'center', alignItems: 'center' }}
      uiBackground={{ texture: { src: IMG.pill }, textureMode: 'stretch', color: toast ? UI.accentTint : WHITE }}
      uiText={{ value, fontSize: 22, color: UI.text, textAlign: 'middle-center' }}
    />
  )
}

// ---------------------------------------------------------------- table card

function TableCard() {
  const t = local.nearTableId >= 0 ? getTable(local.nearTableId) : undefined
  if (!t || !me.ready) return null
  if (mySeatAt(t)) return null // the controller takes over
  if (local.dismissedTableId === t.def.id) return null
  const b = boardOf(t)
  const a = seatOf(t, SEAT_A)
  const s = seatOf(t, SEAT_B)
  const [nameA, nameB] = t.game.seatNames
  const bothTaken = a.addr !== '' && s.addr !== ''
  const line = bothTaken
    ? b.status === Status.Playing
      ? `${a.name} vs ${s.name} · ${b.winsA}:${b.winsB}`
      : `${a.name} vs ${s.name}`
    : a.addr !== ''
      ? `${a.name} is waiting for a rival`
      : s.addr !== ''
        ? `${s.name} is waiting for a rival`
        : `Open table · ${t.game.label}`
  const state = bothTaken ? gameStateOf(t) : null
  return (
    <UiEntity
      uiTransform={{ positionType: 'absolute', position: { bottom: 40, left: '50%' }, margin: { left: -240 }, width: 480, height: 'auto', padding: 18, flexDirection: 'column', alignItems: 'center' }}
      uiBackground={{ texture: { src: IMG.panel }, textureMode: 'stretch' }}
    >
      <Text value={t.def.label} size={28} />
      <Text value={line} size={20} color={UI.muted} margin={{ top: 4, bottom: 10 }} />
      {bothTaken && state !== null && <t.game.Controls state={state} ctx={contextFor(t)} compact={false} />}
      {bothTaken && (
        <Row>
          <Btn label="?" color={UI.panelSoft} onClick={() => (local.helpOpen = true)} width={56} />
          <Btn label="Not now" color={UI.panelSoft} textColor={UI.muted} onClick={() => (local.dismissedTableId = t.def.id)} width={135} />
        </Row>
      )}
      {!bothTaken && (
        <Row>
          {a.addr === '' && <Btn label={`Sit as ${nameA}`} color={UI.yellow} textColor={Color4.Black()} onClick={() => sit(t, SEAT_A)} width={205} />}
          {s.addr === '' && <Btn label={`Sit as ${nameB}`} color={UI.red} onClick={() => sit(t, SEAT_B)} width={205} />}
        </Row>
      )}
      {!bothTaken && (
        <Row>
          {a.addr === '' && s.addr === '' && <Btn label="Play the house bot" color={UI.panelSoft} onClick={() => sitWithBot(t)} width={230} />}
          <Btn label="?" color={UI.panelSoft} onClick={() => (local.helpOpen = true)} width={56} />
          <Btn label="Not now" color={UI.panelSoft} textColor={UI.muted} onClick={() => (local.dismissedTableId = t.def.id)} width={135} />
        </Row>
      )}
    </UiEntity>
  )
}

// ---------------------------------------------------------------- controller

function Controller() {
  const mine = findMySeat()
  if (!mine) return null
  const t = mine.table
  const seat = mine.seat
  const b = boardOf(t)
  const opp = seatOf(t, otherSeat(seat))
  const myTurn = b.status === Status.Playing && b.turn === seat
  const myWins = seat === SEAT_A ? b.winsA : b.winsB
  const oppWins = seat === SEAT_A ? b.winsB : b.winsA
  const mobile = isMobile()
  const compact = mobile && !local.showMiniBoard
  const state = gameStateOf(t)
  const sprites = t.game.seatSprites

  let status = ''
  let statusColor = UI.text
  if (b.status === Status.Waiting) {
    status = opp.addr === '' ? 'Waiting for an opponent…' : 'Dealing…'
    statusColor = UI.muted
  } else if (b.status === Status.Playing) {
    const secs = secondsLeft(b.updatedAt)
    status = myTurn ? `Your move · ${secs}s` : `${opp.name} is thinking… ${secs}s`
    statusColor = myTurn ? seatTint(seat) : UI.muted
  } else if (b.winner === Winner.Draw) status = 'Draw! Well played.'
  else if (b.winner === seat) status = 'You win the round!'
  else status = `${opp.name} takes the round`

  // Desktop docks the panel to the right so the 3D board stays unobstructed;
  // phones keep it bottom-centre, thumb distance from the joystick.
  const placement: UiTransformProps = mobile
    ? { positionType: 'absolute', position: { bottom: 14, left: '50%' }, margin: { left: -240 }, width: 480 }
    : { positionType: 'absolute', position: { right: 36, top: '50%' }, margin: { top: -250 }, width: 420 }

  return (
    <UiEntity uiTransform={{ ...placement, height: 'auto', padding: 14, flexDirection: 'column', alignItems: 'center' }} uiBackground={{ texture: { src: IMG.panel }, textureMode: 'stretch' }}>
      <UiEntity uiTransform={{ width: '100%', height: 'auto', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
        <Chip sprite={sprites[seat - 1]} label={`You · ${t.def.label}`} />
        <UiEntity uiTransform={{ width: 'auto', height: 'auto' }} uiText={{ value: `${myWins} : ${oppWins}`, fontSize: 22, color: UI.text }} />
        <Chip sprite={sprites[otherSeat(seat) - 1]} label={opp.addr === '' ? '—' : opp.name} reverse />
      </UiEntity>

      <Text value={status} size={22} color={statusColor} margin={{ top: 6, bottom: 6 }} />

      {state !== null && <t.game.Controls state={state} ctx={contextFor(t)} compact={compact} />}

      {opp.bot && b.status !== Status.Playing && (
        <Row height={48} margin={{ top: 6 }}>
          <UiEntity uiTransform={{ width: 'auto', height: 30, margin: { right: 6 } }} uiText={{ value: 'Bot:', fontSize: 17, color: UI.muted }} />
          {(['easy', 'medium', 'hard'] as const).map((d) => (
            <UiEntity
              key={d}
              uiTransform={{ width: 86, height: 40, margin: 3, justifyContent: 'center', alignItems: 'center', pointerFilter: 'block' }}
              uiBackground={{ texture: { src: IMG.button }, textureMode: 'stretch', color: local.botDifficulty === d ? UI.accent : UI.panelSoft }}
              uiText={{ value: d[0].toUpperCase() + d.slice(1), fontSize: 16, color: UI.text, textAlign: 'middle-center' }}
              onMouseDown={() => (local.botDifficulty = d)}
            />
          ))}
        </Row>
      )}

      <UiEntity uiTransform={{ width: '100%', height: 'auto', flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', margin: { top: 8 } }}>
        {b.status === Status.Waiting && opp.addr === '' && <Btn label="Play the house bot" onClick={() => inviteBot(t)} />}
        {b.status === Status.Finished && opp.addr !== '' && <Btn label="Play again" onClick={() => rematch(t)} />}
        {opp.bot && b.status !== Status.Playing && <Btn label="Dismiss bot" color={UI.panelSoft} onClick={() => dismissBot(t)} />}
        {mobile && <Btn label={local.showMiniBoard ? 'Hide board' : 'Show board'} color={UI.panelSoft} onClick={() => (local.showMiniBoard = !local.showMiniBoard)} />}
        <Btn label="?" color={UI.panelSoft} onClick={() => (local.helpOpen = true)} width={56} />
        <Btn label="Stand up" color={UI.danger} onClick={() => stand(t)} />
      </UiEntity>
    </UiEntity>
  )
}

// ---------------------------------------------------------------- how to play

/** Which game the help should describe: the table you sit at, else the nearest. */
function helpTable(): Table | undefined {
  const mine = findMySeat()
  if (mine) return mine.table
  return local.nearTableId >= 0 ? getTable(local.nearTableId) : getTable(0)
}

function HelpPanel() {
  if (!local.helpOpen) return null
  const t = helpTable()
  if (!t) return null
  const info = localeInfo(local.lang)
  const str = stringsFor(local.lang)
  const game = info.games[t.game.id]
  const mobile = isMobile()
  const width = mobile ? 760 : 700
  return (
    <UiEntity
      uiTransform={{ positionType: 'absolute', position: { top: 0, left: 0 }, width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center', pointerFilter: 'block' }}
      uiBackground={{ color: Color4.create(0, 0, 0, 0.45) }}
      onMouseDown={() => (local.helpOpen = false)}
    >
      <UiEntity
        uiTransform={{ width, height: 'auto', padding: 20, flexDirection: 'column', alignItems: 'center', pointerFilter: 'block' }}
        uiBackground={{ texture: { src: IMG.panel }, textureMode: 'stretch' }}
        onMouseDown={() => {
          /* swallow clicks inside the panel */
        }}
      >
        <Text value={`${str.howToPlay} · ${game.name}`} size={26} />
        <UiEntity
          uiTransform={{ width: '100%', height: 'auto', margin: { top: 10, bottom: 6 } }}
          uiText={{ value: game.overview, fontSize: 19, color: UI.text, textAlign: info.rtl ? 'top-right' : 'top-left' }}
        />
        <UiEntity uiTransform={{ width: '100%', height: 'auto', margin: { top: 4 } }} uiText={{ value: `• ${str.howToSit}`, fontSize: 18, color: UI.muted, textAlign: info.rtl ? 'top-right' : 'top-left' }} />
        <UiEntity uiTransform={{ width: '100%', height: 'auto', margin: { top: 4 } }} uiText={{ value: `• ${str.move[t.game.id]}`, fontSize: 18, color: UI.muted, textAlign: info.rtl ? 'top-right' : 'top-left' }} />
        <UiEntity uiTransform={{ width: '100%', height: 'auto', margin: { top: 4, bottom: 8 } }} uiText={{ value: `• ${str.timer}`, fontSize: 18, color: UI.muted, textAlign: info.rtl ? 'top-right' : 'top-left' }} />
        <Text value={str.language} size={17} color={UI.muted} margin={{ top: 4 }} />
        <UiEntity uiTransform={{ width: '100%', height: 'auto', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center' }}>
          {LOCALES.map((l) => (
            <UiEntity
              key={l.code}
              uiTransform={{ width: Math.max(92, l.name.length * 11 + 26), height: 40, margin: 3, justifyContent: 'center', alignItems: 'center', pointerFilter: 'block' }}
              uiBackground={{ texture: { src: IMG.button }, textureMode: 'stretch', color: local.lang === l.code ? UI.accent : UI.panelSoft }}
              uiText={{ value: l.name, fontSize: 16, color: UI.text, textAlign: 'middle-center' }}
              onMouseDown={() => (local.lang = l.code)}
            />
          ))}
        </UiEntity>
        <Row margin={{ top: 8 }}>
          <Btn label={str.gotIt} onClick={() => (local.helpOpen = false)} width={180} />
        </Row>
      </UiEntity>
    </UiEntity>
  )
}

// ---------------------------------------------------------------- root

const LoungeUi = () => (
  <UiEntity uiTransform={{ width: '100%', height: '100%', positionType: 'absolute' }}>
    <Banner />
    <TableCard />
    <Controller />
    <HelpPanel />
  </UiEntity>
)
