/**
 * Screen-space UI: the mobile-first controller.
 *
 * On phones, tapping a 3D object means aiming the crosshair and pressing the
 * interaction button, which is slow for a 7-column game. Screen UI is tapped
 * directly, so the UI is the controller and the 3D table is the shared show:
 *  - near a table:  card with the two seat buttons (no pad-hunting needed)
 *  - seated:        mini board (tap a column to drop) + status + actions
 *  - always:        a top banner for onboarding / status and short toasts
 *
 * Visuals come from pre-shaded sprites in images/ui (generated by
 * tools/gen-textures.py) because mobile has no borderRadius / nine-slice;
 * every panel/button is a stretched rounded texture, discs are baked sprites.
 *
 * React hooks are not available in React-ECS; the renderer runs every frame
 * and reads module state + synced components directly.
 */
import { Color4 } from '@dcl/sdk/math'
import ReactEcs, { ReactEcsRenderer, UiEntity, type UiTransformProps } from '@dcl/sdk/react-ecs'
import { isStateSyncronized } from '@dcl/sdk/network'
import { isMobile } from '@dcl/sdk/platform'
import { isColumnPlayable } from '../engine/connectfour'
import { COLS, ROWS } from '../engine/connectfour'
import { TURN_LIMIT_MS, UI } from './config'
import { SEAT_A, SEAT_B, Status, Winner, cellIndex, toEngineState, type Seat } from './state'
import {
  boardOf,
  dismissBot,
  drop,
  findMySeat,
  getTable,
  inviteBot,
  local,
  me,
  mySeatAt,
  otherSeat,
  rematch,
  seatOf,
  sit,
  sitWithBot,
  stand,
  type Table
} from './tables'

export function setupUi(): void {
  ReactEcsRenderer.setUiRenderer(LoungeUi, { virtualWidth: 1920, virtualHeight: 1080 })
}

// ---------------------------------------------------------------- assets

const IMG = {
  panel: 'images/ui/panel.png',
  pill: 'images/ui/pill.png',
  board: 'images/ui/board.png',
  button: 'images/ui/button.png',
  yellow: 'images/ui/disc-yellow.png',
  red: 'images/ui/disc-red.png',
  hole: 'images/ui/hole.png',
  ring: 'images/ui/ring.png'
}

const CELL = 40
const CELL_GAP = 4
const WHITE = Color4.White()

type Margin = UiTransformProps['margin']
type Width = UiTransformProps['width']

function seatSprite(seat: Seat): string {
  return seat === SEAT_A ? IMG.yellow : IMG.red
}
function seatTint(seat: Seat): Color4 {
  return seat === SEAT_A ? UI.yellow : UI.red
}

// ---------------------------------------------------------------- atoms

function Btn(props: {
  label: string
  onClick: () => void
  color?: Color4
  textColor?: Color4
  width?: Width
  fontSize?: number
  margin?: Margin
}) {
  return (
    <UiEntity
      uiTransform={{
        width: props.width ?? 'auto',
        minWidth: 130,
        height: 56,
        margin: props.margin ?? 5,
        padding: { left: 18, right: 18 },
        justifyContent: 'center',
        alignItems: 'center',
        pointerFilter: 'block'
      }}
      uiBackground={{ texture: { src: IMG.button }, textureMode: 'stretch', color: props.color ?? UI.accent }}
      uiText={{
        value: props.label,
        fontSize: props.fontSize ?? 21,
        color: props.textColor ?? UI.text,
        textAlign: 'middle-center'
      }}
      onMouseDown={props.onClick}
    />
  )
}

/** Centred single line of text. Needs an explicit height: with height 'auto'
 *  the renderer ignores textAlign and draws the text top-left. */
function Text(props: { value: string; size?: number; color?: Color4; margin?: Margin; width?: Width }) {
  const size = props.size ?? 20
  return (
    <UiEntity
      uiTransform={{ width: props.width ?? '100%', height: Math.round(size * 1.45), margin: props.margin ?? 0, justifyContent: 'center', alignItems: 'center' }}
      uiText={{ value: props.value, fontSize: size, color: props.color ?? UI.text, textAlign: 'middle-center' }}
    />
  )
}

function Chip(props: { sprite: string; label: string; reverse?: boolean }) {
  const disc = (
    <UiEntity
      uiTransform={{ width: 26, height: 26, margin: props.reverse ? { left: 8 } : { right: 8 } }}
      uiBackground={{ texture: { src: props.sprite }, textureMode: 'stretch' }}
    />
  )
  const label = (
    <UiEntity uiTransform={{ width: 'auto', height: 'auto' }} uiText={{ value: props.label, fontSize: 19, color: UI.text }} />
  )
  return (
    <UiEntity uiTransform={{ width: 'auto', height: 30, flexDirection: 'row', alignItems: 'center' }}>
      {props.reverse ? label : disc}
      {props.reverse ? disc : label}
    </UiEntity>
  )
}

function secondsLeft(updatedAt: number): number {
  return Math.max(0, Math.ceil((TURN_LIMIT_MS - (Date.now() - updatedAt)) / 1000))
}

// ---------------------------------------------------------------- top banner

function bannerText(): string {
  if (!me.ready) return 'Loading your profile…'
  if (!isStateSyncronized() && !local.offline) return 'Connecting to the lounge…'
  if (findMySeat()) return ''
  if (!local.hasEverSat) return 'Walk up to a table and tap a seat to play'
  return ''
}

function Banner() {
  const text = bannerText()
  const toast = local.toast.until > Date.now() ? local.toast.text : ''
  const value = toast || text
  if (!value) return null
  return (
    <UiEntity
      uiTransform={{
        positionType: 'absolute',
        position: { top: 18, left: '50%' },
        margin: { left: -280 },
        width: 560,
        height: 60,
        justifyContent: 'center',
        alignItems: 'center'
      }}
      uiBackground={{ texture: { src: IMG.pill }, textureMode: 'stretch', color: toast ? UI.accentTint : WHITE }}
      uiText={{ value, fontSize: 22, color: UI.text, textAlign: 'middle-center' }}
    />
  )
}

// ---------------------------------------------------------------- table card

function TableCard() {
  const t = local.nearTableId >= 0 ? getTable(local.nearTableId) : undefined
  if (!t || !me.ready) return null
  if (mySeatAt(t)) return null // the controller takes over
  if (local.dismissedTableId === t.def.id) return null
  const b = boardOf(t)
  const a = seatOf(t, SEAT_A)
  const s = seatOf(t, SEAT_B)
  const bothTaken = a.addr !== '' && s.addr !== ''
  const line = bothTaken
    ? b.status === Status.Playing
      ? `${a.name} vs ${s.name} · ${b.winsA}:${b.winsB}`
      : `${a.name} vs ${s.name}`
    : a.addr !== ''
      ? `${a.name} is waiting for a rival`
      : s.addr !== ''
        ? `${s.name} is waiting for a rival`
        : 'Open table · Connect Four'
  return (
    <UiEntity
      uiTransform={{
        positionType: 'absolute',
        position: { bottom: 40, left: '50%' },
        margin: { left: -240 },
        width: 480,
        height: 'auto',
        padding: 18,
        flexDirection: 'column',
        alignItems: 'center'
      }}
      uiBackground={{ texture: { src: IMG.panel }, textureMode: 'stretch' }}
    >
      <Text value={t.def.label} size={28} />
      <Text value={line} size={20} color={UI.muted} margin={{ top: 4, bottom: 10 }} />
      {bothTaken ? (
        <Text value="Both seats are taken. Watch, or try another table." size={18} color={UI.muted} />
      ) : (
        <UiEntity uiTransform={{ width: '100%', height: 'auto', flexDirection: 'column', alignItems: 'center' }}>
          <UiEntity uiTransform={{ width: '100%', height: 'auto', flexDirection: 'row', justifyContent: 'center' }}>
            {a.addr === '' && (
              <Btn label="Sit as Yellow" color={UI.yellow} textColor={Color4.Black()} onClick={() => sit(t, SEAT_A)} width={205} />
            )}
            {s.addr === '' && <Btn label="Sit as Red" color={UI.red} onClick={() => sit(t, SEAT_B)} width={205} />}
          </UiEntity>
          <UiEntity uiTransform={{ width: '100%', height: 'auto', flexDirection: 'row', justifyContent: 'center' }}>
            {a.addr === '' && s.addr === '' && (
              <Btn label="Play the house bot" color={UI.panelSoft} onClick={() => sitWithBot(t)} width={275} />
            )}
            <Btn label="Not now" color={UI.panelSoft} textColor={UI.muted} onClick={() => (local.dismissedTableId = t.def.id)} width={135} />
          </UiEntity>
        </UiEntity>
      )}
    </UiEntity>
  )
}

// ---------------------------------------------------------------- controller

function MiniBoard(props: { table: Table; interactive: boolean }) {
  const b = boardOf(props.table)
  const winSet = new Set(b.winCells)
  const columns = []
  for (let c = 0; c < COLS; c++) {
    const cells = []
    for (let r = 0; r < ROWS; r++) {
      const idx = cellIndex(r, c)
      const v = b.cells[idx] ?? 0
      const highlight = winSet.has(idx) || (idx === b.lastCell && b.winCells.length === 0)
      cells.push(
        <UiEntity
          key={`c${idx}`}
          uiTransform={{ width: CELL, height: CELL, margin: CELL_GAP / 2, justifyContent: 'center', alignItems: 'center' }}
          uiBackground={{ texture: { src: v === 0 ? IMG.hole : v === 1 ? IMG.yellow : IMG.red }, textureMode: 'stretch' }}
        >
          {highlight && (
            <UiEntity uiTransform={{ width: CELL, height: CELL }} uiBackground={{ texture: { src: IMG.ring }, textureMode: 'stretch' }} />
          )}
        </UiEntity>
      )
    }
    columns.push(
      <UiEntity
        key={`col${c}`}
        uiTransform={{ flexDirection: 'column', width: 'auto', height: 'auto', pointerFilter: 'block' }}
        onMouseDown={() => {
          if (props.interactive) drop(props.table, c)
        }}
      >
        {cells}
      </UiEntity>
    )
  }
  return (
    <UiEntity
      uiTransform={{ flexDirection: 'row', width: 'auto', height: 'auto', padding: 8 }}
      uiBackground={{ texture: { src: IMG.board }, textureMode: 'stretch' }}
    >
      {columns}
    </UiEntity>
  )
}

/** Seven big drop buttons, one per column, showing the player's disc. */
function DropStrip(props: { table: Table; seat: Seat; interactive: boolean }) {
  const b = boardOf(props.table)
  const grid = toEngineState(b).board
  const buttons = []
  for (let c = 0; c < COLS; c++) {
    const playable = props.interactive && isColumnPlayable(grid, c)
    buttons.push(
      <UiEntity
        key={`d${c}`}
        uiTransform={{
          width: 62,
          height: 66,
          margin: 3,
          justifyContent: 'center',
          alignItems: 'center',
          pointerFilter: 'block',
          opacity: playable ? 1 : 0.35
        }}
        uiBackground={{ texture: { src: IMG.button }, textureMode: 'stretch', color: UI.boardBg }}
        onMouseDown={() => {
          if (playable) drop(props.table, c)
        }}
      >
        <UiEntity uiTransform={{ width: 40, height: 40 }} uiBackground={{ texture: { src: seatSprite(props.seat) }, textureMode: 'stretch' }} />
      </UiEntity>
    )
  }
  return <UiEntity uiTransform={{ flexDirection: 'row', width: 'auto', height: 'auto' }}>{buttons}</UiEntity>
}

function Controller() {
  const mine = findMySeat()
  if (!mine) return null
  const t = mine.table
  const seat = mine.seat
  const b = boardOf(t)
  const opp = seatOf(t, otherSeat(seat))
  const myTurn = b.status === Status.Playing && b.turn === seat
  const myWins = seat === SEAT_A ? b.winsA : b.winsB
  const oppWins = seat === SEAT_A ? b.winsB : b.winsA
  const mobile = isMobile()
  const showBoard = !mobile || local.showMiniBoard

  let status = ''
  let statusColor = UI.text
  if (b.status === Status.Waiting) {
    status = opp.addr === '' ? 'Waiting for an opponent…' : 'Dealing…'
    statusColor = UI.muted
  } else if (b.status === Status.Playing) {
    const secs = secondsLeft(b.updatedAt)
    status = myTurn ? `Your move · ${secs}s` : `${opp.name} is thinking… ${secs}s`
    statusColor = myTurn ? seatTint(seat) : UI.muted
  } else if (b.winner === Winner.Draw) status = 'Draw! Well played.'
  else if (b.winner === seat) status = 'You win the round!'
  else status = `${opp.name} takes the round`

  // Desktop docks the panel to the right so the 3D board stays unobstructed;
  // phones keep it bottom-centre, thumb distance from the joystick.
  const placement: UiTransformProps = mobile
    ? { positionType: 'absolute', position: { bottom: 14, left: '50%' }, margin: { left: -240 }, width: 480 }
    : { positionType: 'absolute', position: { right: 36, top: '50%' }, margin: { top: -250 }, width: 420 }

  return (
    <UiEntity
      uiTransform={{ ...placement, height: 'auto', padding: 14, flexDirection: 'column', alignItems: 'center' }}
      uiBackground={{ texture: { src: IMG.panel }, textureMode: 'stretch' }}
    >
      <UiEntity uiTransform={{ width: '100%', height: 'auto', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
        <Chip sprite={seatSprite(seat)} label={`You · ${t.def.label}`} />
        <UiEntity uiTransform={{ width: 'auto', height: 'auto' }} uiText={{ value: `${myWins} : ${oppWins}`, fontSize: 22, color: UI.text }} />
        <Chip sprite={seatSprite(otherSeat(seat))} label={opp.addr === '' ? '—' : opp.name} reverse />
      </UiEntity>

      <Text value={status} size={22} color={statusColor} margin={{ top: 6, bottom: 6 }} />

      {showBoard ? <MiniBoard table={t} interactive={myTurn} /> : <DropStrip table={t} seat={seat} interactive={myTurn} />}

      <UiEntity uiTransform={{ width: '100%', height: 'auto', flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', margin: { top: 8 } }}>
        {b.status === Status.Waiting && opp.addr === '' && <Btn label="Play the house bot" onClick={() => inviteBot(t)} />}
        {b.status === Status.Finished && opp.addr !== '' && <Btn label="Play again" onClick={() => rematch(t)} />}
        {opp.bot && b.status !== Status.Playing && <Btn label="Dismiss bot" color={UI.panelSoft} onClick={() => dismissBot(t)} />}
        {mobile && (
          <Btn
            label={local.showMiniBoard ? 'Hide board' : 'Show board'}
            color={UI.panelSoft}
            onClick={() => (local.showMiniBoard = !local.showMiniBoard)}
          />
        )}
        <Btn label="Stand up" color={UI.danger} onClick={() => stand(t)} />
      </UiEntity>
    </UiEntity>
  )
}

// ---------------------------------------------------------------- root

const LoungeUi = () => (
  <UiEntity uiTransform={{ width: '100%', height: '100%', positionType: 'absolute' }}>
    <Banner />
    <TableCard />
    <Controller />
  </UiEntity>
)
