#!/usr/bin/env python3
"""Pack every sprite in tools/sprites/*.png into one sheet, images/ui/atlas.png, and write the
matching TypeScript map src/lounge/atlas.gen.ts (pixel rects). One texture instead of ~36:
fewer requests against the content gateway and a fraction of the mobile texture budget.

Simple shelf packing on 128 px rows (sprites are 64, 128, 256x64, 512x128, 256x256), 2 px gutters
so bilinear filtering never bleeds into the neighbour. Run after tools/gen-textures.py:
    python3 tools/gen-atlas.py
"""
import os, json
from PIL import Image

SRC = 'tools/sprites'
OUT_PNG = 'images/ui/atlas.png'
OUT_TS = 'src/lounge/atlas.gen.ts'
GUTTER = 2
W = 1024

names = sorted(f[:-4] for f in os.listdir(SRC) if f.endswith('.png') and f != 'atlas.png')
imgs = {n: Image.open(f'{SRC}/{n}.png').convert('RGBA') for n in names}
# tallest first, then widest: rows fill better
order = sorted(names, key=lambda n: (-imgs[n].height, -imgs[n].width, n))
rects = {}
x = y = row_h = 0
for n in order:
    w, h = imgs[n].size
    if x + w + GUTTER > W:
        x = 0; y += row_h + GUTTER; row_h = 0
    rects[n] = (x, y, w, h)
    x += w + GUTTER
    row_h = max(row_h, h)
H = y + row_h
H = 1 << (H - 1).bit_length()          # power of two height
sheet = Image.new('RGBA', (W, H), (0, 0, 0, 0))
for n, (rx, ry, w, h) in rects.items():
    sheet.paste(imgs[n], (rx, ry))
    # 1 px edge bleed into the gutter so filtering at the sprite border stays clean
    im = imgs[n]
    sheet.paste(im.crop((0, 0, w, 1)), (rx, ry - 1)) if ry > 0 else None
    sheet.paste(im.crop((0, h - 1, w, h)), (rx, ry + h))
    sheet.paste(im.crop((0, 0, 1, h)), (rx - 1, ry)) if rx > 0 else None
    sheet.paste(im.crop((w - 1, 0, w, h)), (rx + w, ry))
sheet.save(OUT_PNG, optimize=True)
lines = ["// Generated by tools/gen-atlas.py: pixel rects of every sprite in images/ui/atlas.png. Do not edit.",
         f"export const ATLAS_SIZE = [{W}, {H}] as const",
         "export const SPRITES = {"]
for n in names:
    rx, ry, w, h = rects[n]
    lines.append(f"  '{n}': [{rx}, {ry}, {w}, {h}],")
lines.append("} as const")
lines.append("export type SpriteName = keyof typeof SPRITES")
open(OUT_TS, 'w').write('\n'.join(lines) + '\n')
print(f'wrote {OUT_PNG} {W}x{H} with {len(names)} sprites, {os.path.getsize(OUT_PNG) // 1024} KB; {OUT_TS}')
